/******************************************************************************

  Copyright (C), 2001-2011, Hisilicon Tech. Co., Ltd.
 ******************************************************************************
 File Name     : mpi_errdef.h
Version       : Initial Draft
Author        : Hisilicon multimedia software group
Created       : 2006/3/6
Last Modified :
Description   : 系统共用的错误码定义
Function List :
History       :
 ******************************************************************************/
#ifndef __SYNC_ERRCODE_H__
#define __SYNC_ERRCODE_H__


#ifdef __cplusplus
#if __cplusplus
extern "C"{
#endif
#endif /* __cplusplus */

/********************************************************
  SYNC错误码定义
 *********************************************************/

#define MID_SYNC 0x21/*SYNC模块ID*/

typedef enum hiSync_ErrorCode 
{
    ERR_SYNC_DEV_OPENNED = 0x00,      /* 设备重复打开 */
    ERR_SYNC_PTR_NULL  = 0x01,
    ERR_SYNC_IOREMAP_FAIL = 0x02,         /* IO映射失败 */
    ERR_SYNC_CREATE_DEV_FAIL = 0x03,      /* 注册设备失败 */
    ERR_SYNC_INVALID_PARAMETER = 0x04,    /* 无效参数 */
    ERR_SYNC_MEMALLOC_FAIL = 0x05,        /* 内存分配失败 */
    ERR_SYNC_INVALID_PLAYBACK_MODE = 0x06,
    ERR_SYNC_DEV_NO_OPEN = 0x07,
    ERR_SYNC_AUD_CHANNEL_OPENED = 0x08,
    ERR_SYNC_AUD_INVALID_STREAM = 0x09,
    ERR_SYNC_AUD_DECODER_NOT_STOPPED = 0x0a,
    ERR_SYNC_GET_AUD_PLAYBACK_TIME = 0x0b,
    ERR_SYNC_VID_CHANNEL_OPENED = 0x0c,
    ERR_SYNC_VID_INVALID_STREAM = 0x0d,
    ERR_SYNC_VID_DECODER_NOT_STOPPED = 0x0e,
    ERR_SYNC_GET_VID_PLAYBACK_TIME = 0x0f,
    ERR_SYNC_GET_PLAYBACK_TIME = 0x10,
    ERR_SYNC_FIND_PTS = 0x11,
    ERR_SYNC_NO_MACH_FOR_AUD = 0x12,
    ERR_SYNC_NO_MACH_FOR_VID = 0x13,
    ERR_SYNC_INVALID_MODE = 0x14,
    ERR_SYNC_INVALID_ADJUST = 0x15,
    ERR_SYNC_INVALID_PES_SOURCE = 0x16
}SYNC_ERROR;

/*SYNC错误码定义*/
#define HI_ERR_SYNC_DEV_OPENNED\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_DEV_OPENNED)

#define HI_ERR_SYNC_PTR_NULL\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_PTR_NULL)

#define HI_ERR_SYNC_IOREMAP_FAIL\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_IOREMAP_FAIL)
#define HI_ERR_SYNC_CREATE_DEV_FAIL\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_CREATE_DEV_FAIL)
#define HI_ERR_SYNC_INVALID_PARAMETER\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_INVALID_PARAMETER)
#define HI_ERR_SYNC_MEMALLOC_FAIL\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_MEMALLOC_FAIL)

#define HI_ERR_SYNC_INVALID_MODE\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_INVALID_MODE)

#define HI_ERR_SYNC_INVALID_PLAYBACK_MODE\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_INVALID_PLAYBACK_MODE)

#define HI_ERR_SYNC_DEV_NO_OPEN\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_DEV_NO_OPEN)

#define HI_ERR_SYNC_AUD_CHANNEL_OPENED\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_AUD_CHANNEL_OPENED)

#define HI_ERR_SYNC_AUD_INVALID_STREAM\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_AUD_INVALID_STREAM)

#define HI_ERR_SYNC_AUD_DECODER_NOT_STOPPED\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_AUD_DECODER_NOT_STOPPED)

#define HI_ERR_SYNC_GET_AUD_PLAYBACK_TIME\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_GET_AUD_PLAYBACK_TIME)

#define HI_ERR_SYNC_VID_CHANNEL_OPENED\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_VID_CHANNEL_OPENED)

#define HI_ERR_SYNC_VID_INVALID_STREAM\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_VID_INVALID_STREAM)

#define HI_ERR_SYNC_VID_DECODER_NOT_STOPPED\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_VID_DECODER_NOT_STOPPED)

#define HI_ERR_SYNC_FIND_PTS\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_FIND_PTS)

#define HI_ERR_SYNC_GET_VID_PLAYBACK_TIME\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_GET_VID_PLAYBACK_TIME)

#define HI_ERR_SYNC_GET_PLAYBACK_TIME\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_GET_PLAYBACK_TIME)
    
#define HI_ERR_SYNC_NO_MACH_FOR_AUD\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_NO_MACH_FOR_AUD)

#define HI_ERR_SYNC_NO_MACH_FOR_VID\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_NO_MACH_FOR_VID)
    
#define HI_ERR_SYNC_INVALID_ADJUST\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_INVALID_ADJUST)
    
#define HI_ERR_SYNC_INVALID_PES_SOURCE\
    HI_DEF_ERR(MID_SYNC, HI_LOG_LEVEL_ERROR, ERR_SYNC_INVALID_PES_SOURCE)



#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif /* __MPI_ERRDEF_H__ */

