/******************************************************************************

  Copyright (C), 2001-2011, Hisilicon Tech. Co., Ltd.
 ******************************************************************************
 File Name     : audio_errcode.h
Version       : Initial Draft
Author        : Hisilicon multimedia software group
Created       : 2006/3/6
Last Modified :
Description   : 系统共用的错误码定义
Function List :
History       :
 ******************************************************************************/
#ifndef __VBI_ERRCODE_H__
#define __VBI_ERRCODE_H__

#ifdef __cplusplus
#if __cplusplus
extern "C"{
#endif
#endif /* __cplusplus */

/********************************************************
  VBI Errorcode
 *********************************************************/
#define MID_VBI 0x24/*VBI moudle ID*/

enum hiVBI_ErrorCode
{
    ERR_VBI_NO_OPEN = 0,
    ERR_VBI_OPENED,
    ERR_VBI_INVALID_STREAM_SOURCE,
    ERR_VBI_CHANNEL_OPENNING,
    ERR_VBI_RUNNING_STATUS,    
    ERR_VBI_STOPPED_STATUS,
    ERR_VBI_PARSE_UNFINISHED,
    ERR_VBI_INVALID_VBI_TYPE,
    ERR_VBI_INVAILD_CHANNELID,
    ERR_VBI_DATA_INVAILD_PACKETLENGTH,
    ERR_VBI_INVALID_STATUS_TRANSFER,
    ERR_VBI_DATA_NO_PES_HEAD,
    ERR_VBI_INVAILD_IDENTIFER,
    
    ERR_VBI_ENGINE_RUNNING_STATUS,

    ERR_VBI_MACROVISION_UNSUPPORTED,
    ERR_VBI_INVALID_ENCODE_MODE,
    ERR_VBI_MACROVISION_ALREADY_DISABLE,
    ERR_VBI_MACROVISION_INVALID_CONTROL_MODE,
    ERR_VBI_MACROVISION_INVALID_REDUCE_MODE,
    ERR_VBI_PTR_NULL,
    ERR_VBI_TOO_FEW_TO_COPY,
};

#define HI_ERR_VBI_NO_OPEN\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_NO_OPEN)

#define HI_ERR_VBI_OPENED\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_OPENED)

#define HI_ERR_VBI_RUNNING_STATUS\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_RUNNING_STATUS)

#define HI_ERR_VBI_STOPPED_STATUS\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_STOPPED_STATUS)

#define HI_ERR_VBI_PARSE_UNFINISHED\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_PARSE_UNFINISHED)

#define HI_ERR_VBI_INVALID_STATUS_TRANSFER\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_INVALID_STATUS_TRANSFER)

#define HI_ERR_VBI_CHANNEL_OPENNING\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_CHANNEL_OPENNING)

#define HI_ERR_VBI_DATA_INVAILD_IDENTIFER\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_INVAILD_IDENTIFER)

#define HI_ERR_VBI_INVALID_STREAM_SOURCE\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_INVALID_STREAM_SOURCE)

#define HI_ERR_VBI_INVALID_VBI_TYPE\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_INVALID_VBI_TYPE)

#define HI_ERR_VBI_DATA_NO_PES_HEAD\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_DATA_NO_PES_HEAD)

#define HI_ERR_VBI_INVAILD_CHANNELID\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_INVAILD_CHANNELID)

#define HI_ERR_VBI_DATA_INVAILD_PACKETLENGTH\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_DATA_INVAILD_PACKETLENGTH)

#define HI_ERR_VBI_ENGINE_RUNNING_STATUS\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_ENGINE_RUNNING_STATUS)

#define HI_ERR_VBI_INVALID_ENCODE_MODE\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_INVALID_ENCODE_MODE)

#define HI_ERR_VBI_MACROVISION_UNSUPPORTED\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_MACROVISION_UNSUPPORTED)

#define HI_ERR_VBI_MACROVISION_INVALID_CONTROL_MODE\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_MACROVISION_INVALID_CONTROL_MODE)

#define HI_ERR_VBI_MACROVISION_INVALID_REDUCE_MODE\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_MACROVISION_INVALID_REDUCE_MODE)

#define HI_ERR_VBI_MACROVISION_ALREADY_DISABLE\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_MACROVISION_ALREADY_DISABLE)

#define HI_ERR_VBI_PTR_NULL\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_PTR_NULL)

#define HI_ERR_VBI_TOO_FEW_TO_COPY\
    HI_DEF_ERR(MID_VBI, HI_LOG_LEVEL_ERROR, ERR_VBI_TOO_FEW_TO_COPY)

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif /* __VBI_ERRCODE_H__ */

