#ifndef __WNDID_H_
#define __WNDID_H_

typedef enum
{
//主菜单

ID_DLG_MainMenu,
ID_STA_CardState_MainMenu,
ID_STA_Time_MainMenu,
ID_VFM_MainMenu,
ID_ODC_MainMenu,
ID_TIM_MainMenu,

//空对话框

ID_DLG_Null,
ID_STA_MUTE_EVM_BAK,
ID_STA_MUTE_EVM,
ID_STA_VOI_EVM_BAK,
ID_VOI_EVM,
ID_STA_NULL_CHECKNET,
ID_STA_NULL_CHECKNET_BAK,
ID_TIM_NULL,

//无节目自动搜索提示框

ID_DLG_AutoInfo,
ID_STA_Line1_AutoInfo,
ID_STA_Line2_AutoInfo,
ID_STA_Line3_AutoInfo,
ID_STA_Bk_AutoInfo,
ID_VFM_AutoInfo,
ID_TIM_AutoInfo,

//节目管理

ID_DLG_ProgManager,
ID_STA_CardState_ProgramManager,
ID_VFM_ProgManager,
ID_MNU_ProgManager,
ID_STA_event1_progmanager,
ID_STA_event2_progmanager,
ID_STA_OkIco_ProgManager,
ID_STA_EnterMenu_ProgManager,
ID_STA_ExitIco_ProManager,
ID_STA_ExitMenu_ProgManager,
ID_STA_Time_ProgManager,
ID_PBR_Epg_ProgManager,

//节目列表

ID_DLG_ProgList,
ID_STA_ProgList_ProgList,
ID_STA_CardState_ProgList,
ID_VFM_ProgList,
ID_LBP_Prog_ProgList,
ID_STA_event1_ProgList,
ID_STA_event2_ProgList,
ID_TIM_ProgList,
ID_SBR_ProgList,
ID_STA_ExitIco_ProgList,
ID_STA_MenuExit_ProgList,
ID_STA_OkIco_ProgList,
ID_STA_View_ProgList,
ID_STA_Time_ProgList,
ID_STA_SelectLR_RrogList,
ID_STA_Scan_ProgList,
ID_STA_SwitchPage_ProgList,
ID_PBR_Epg_ProgList,
ID_STA_ProgList,

//系统提示

ID_DLG_SysInfo,
ID_STA_Menu_SysInfo,
ID_STA_Line1_SysInfo,
ID_TIM_SysInfo,

//全屏节目信息

ID_DLG_ChnInfo,
ID_TIM_ChnInfo,
ID_TIM_Event_ChnInfo,
ID_STA_Text_ChnInfo,
ID_STA_Title_ChnInfo,
ID_STA_TextBk_ChnInfo,
ID_STAText1_ChnInfo,
ID_STAText2_ChnInfo,
ID_STAText3_ChnInfo,
ID_STAText4_ChnInfo,
ID_STABar1_ChnInfo,
ID_STABar2_ChnInfo,
ID_STABar3_ChnInfo,
ID_ODC_ChName_ChnInfo,
ID_CBX_Track_ChnInfo,
ID_CBX_Offset_ChnInfo,
ID_STADLgBK_ChnInfo,
ID_STA_Track_ChnInfo,
ID_STA_Time_ChnInfo,
ID_STA_Info1_ChnInfo,
ID_STA_Info2_ChnInfo,
ID_STA_Name_ChnInfo,
ID_STA_NameBk_ChnInfo,
ID_STAIcon1_ChnInfo,
ID_STAIcon2_ChnInfo,
ID_STAIcon3_ChnInfo,
ID_PBR_Epg_ChnInfo,
ID_ODC_ADV_ChnInfo,
ID_STA_InfoBK_ChnInfo,
ID_STA_Relogo,
ID_STA_FULLSCREEN_CHECKNET_BAK,
ID_CHN_ChnInfo,
ID_STAMute_ChnInfo,
ID_STAMuteBk_ChnInfo,
ID_VOI_ChnInfo,
ID_STAVOI_ChnInfo,
ID_STA_Mail_ChInfo,
ID_STA_HideMail_ChInfo,
ID_STA_ipp_bk_ChnInfo,
ID_STA_ipp_title_ChnInfo,
ID_STA_ipp_tvsid_ChnInfo,
ID_STA_ipp_productid_ChnInfo,
ID_STA_ipp_slotid_ChnInfo,
ID_STA_ipp_ExpiredDate_ChnInfo,
ID_LBX_ipp_price_ChnInfo,
ID_STA_ipp_pin_ChnInfo,
ID_STA_ipp_pin_prompt_ChnInfo,
ID_TBX_ipp_pin_ChnInfo,
ID_STA_ipp_prompt_ChnInfo,
ID_STA_ipp_prompt2_ChnInfo,
ID_ODC_CaOsd_ChInfo,
ID_TIM_CaOsd_ChInfo,
ID_STA_Text1_ChInfo,
ID_STA_FULLSCREEN_CHECKNET,
ID_STA_Text2_ChInfo,
ID_PBR_ChInfo,
ID_STA_ipp_price_ChnInfo,
ID_STA_UrgentBrct_ChnInfo,
ID_STA_FullTrans1_ChInfo,
ID_STA_FullTrans2_ChInfo,
ID_TIM_NETSTATE,
ID_STA_HideTextBk_ChnInfo,
ID_STABK_ChnInfo,

//分类列表

ID_DLG_SortProgram,
ID_STA_Note_SortProgram,
ID_STA_NoteBk_SortProgram,
ID_STA_ProgList_SortProgram,
ID_STA_CardState_SortProgram,
ID_VFM_SortProgram,
ID_LBP_SortProgram,
ID_STA_event1_SortProgram,
ID_STA_event2_SortProgram,
ID_TIM_SortProgram,
ID_SBR_SortProgram,
ID_STA_Time_SortProgram,
ID_STA_Sort_SortProgram,
ID_PBR_Epg_SortProgram,
ID_STA_ListTitleBk_SortProgram,
ID_STA_ExitIco_SortProgram,
ID_STA_MenuExit_SortProgram,
ID_STA_OkIco_SortProgram,
ID_STA_View_SortProgram,
ID_STA_SelectLR_SortProgram,
ID_STA_Scan_SortProgram,
ID_STA_SwitchPage_SortProgram,

//搜素节目

ID_DLG_Search,
ID_PBR_Snr_Search,
ID_PBR_Progress_Search,
ID_STA_Search,
ID_STA_Menu_Search,
ID_LBX_TV_Search,
ID_LBX_Radio_Search,
ID_STA_Line1_Search,
ID_STA_Line2_Search,
ID_STA_StrengthNum_Search,
ID_STA_ProgressNum_Search,
ID_STA_Freq_Search,
ID_STA_ExitIco_Search,
ID_STA_Time_Search,
ID_STA_TVNum_Search,
ID_STA_RadioNum_Search,

//搜索节目结束提示框

ID_DLG_SearchInfo,
ID_STA_Menu_SearchInfo,
ID_STA_Line1_SearchInfo,
ID_STA_Line2_SearchInfo,
ID_STA_Line3_SearchInfo,
ID_TIM_SearchInfo,

//手动搜索设置

ID_DLG_ManualSearchSet,
ID_PBR_Strength_ManualSearchSet,
ID_PBR_Snr_ManualSearchSet,
ID_STA_Menu_ManualSearchSet,
ID_CBX_QAM_ManualSearchSet,
ID_CBX_NetSearch_ManualSearchSet,
ID_STA_StartFre_ManualSearchSet,
ID_STA_StopFre_ManualSearchSet,
ID_STA_SignalFre_ManualSearchSet,
ID_STA_ModuMode_ManualSearchSet,
ID_STA_NetSearch_ManualSearchSet,
ID_TBX_StartFreq_ManualSearchSet,
ID_TBX_EndFreq_ManualSearchSet,
ID_TBX_SymbRate_ManualSearchSet,
ID_STA_InNum_ManualSearchSet,
ID_STA_ExitMenu_ManualSearchSet,
ID_STA_StartSrch_ManualSearchSet,
ID_STA_SigVoltage_ManualSearchSet,
ID_STA_SNR_ManualSearchSet,
ID_STA_StrengthStr_ManualSearchSet,
ID_STA_SnrStr_ManualSearchSet,
ID_TIM_ManualSearchSet,
ID_STA_NumIco_ManualSearchSet,
ID_STA_ExitIco_ManualSearchSet,
ID_STA_OkIco_ManualSearchSet,
ID_STA_Time_ManualSearchSet,

//菜单锁

ID_DLG_MenuLock,
ID_TIM_MenuLock,
ID_ODC_MenuLock,
ID_STA_Tex_MenuLock,
ID_STA_Line1_MenuLock,

//频道锁

ID_DLG_ChnLock,
ID_TIM_ChnLock,
ID_ODC_ChnLock,
ID_STA_Menu_ChnLock,
ID_STA_Tex_ChnLock,

//是否一次性解锁提示框

ID_DLG_Unlock,
ID_STA_Unlock,
ID_STA_Line1_Unlock,
ID_STA_Line2_Unlock,

//主频点设置

ID_DLG_MainFreqSet,
ID_STA_Menu_MainFreqSet,
ID_STA_CardState_MainFreqSet,
ID_VFM_MainFreqSet,
ID_STA_event1_MainFreqSet,
ID_STA_event2_MainFreqSet,
ID_CBX_Ctr_MainFreqSet,
ID_TBX_MainFreqSet_MainFreqSet,
ID_CBX_OnOff_MainFreqSet,
ID_CBX_FreqSet_MainFreqSet,
ID_STA_Time_MainFreqSet,
ID_STA_ExitIco_MainFreqSet,
ID_STA_MenuExit_MainFreqSet,
ID_STA_EnterNum_MainFreqSet,
ID_PBR_Epg_MainFreqSet,

//节目编辑

ID_DLG_ChannelEdit,
ID_STA_CardState_ChannelEdit,
ID_VFM_ChannelEdit,
ID_LBP_ChannelEdit,
ID_SBR_ChannelEdit,
ID_STA_Menu_ChannelEdit,
ID_STA_event1_ChannelEdit,
ID_STA_event2_ChannelEdit,
ID_TIM_ChannelEdit,
ID_STA_Ok_ChannelEdit,
ID_STA_Exit_ChannelEdit,
ID_STA_OkIco_ChannelEdit,
ID_STA_ExitIco_ChannelEdit,
ID_STA_Time_ChannelEdit,
ID_STA_EditSort_ChannelEdit,
ID_PBR_Epg_ChannelEdit,

//节目编辑结束提示框

ID_DLG_EditInfo,
ID_STA_Line1_EditInfo,
ID_STA_Menu_EditInfo,
ID_TIM_EditInfo,

//数据广播列表

ID_DLG_BroadcastList,
ID_STA_Menu_BroadcastList,
ID_STA_CardState_BroadcastList,
ID_VFM_BroadcastList,
ID_LBP_BroadcastList,
ID_STA_event1_BroadcastList,
ID_STA_event2_BroadcastList,
ID_SBR_BroadcastList,
ID_CBX_BroadcastList,
ID_STA_ExitIco_BroadcastList,
ID_STA_MenuExit_BroadcastList,
ID_STA_OkIco_BroadcastList,
ID_STA_View_BroadcastList,
ID_STA_Time_BroadcastList,
ID_PBR_Epg_BroadcastList,

//EPG

ID_DLG_EPG,
ID_LBP_Prog_EPG,
ID_TAB_EPG,
ID_SBR_Event_EPG,
ID_STA_EventName_Detail,
ID_EDT_Detail_EPG,
ID_LBP_Event_EPG,
ID_SBR_Prog_EPG,
ID_STA_CardState_EPG,
ID_VFM_EPG,
ID_STA_PreDay_EPG,
ID_STA_ResProg_EPG,
ID_STA_Epg_EPG,
ID_STA_Time_EPG,
ID_STA_ReturnIco_EPG,
ID_STA_Return_EPG,
ID_STA_OkIcon_EPG,
ID_STA_GreenIcon_EPG,
ID_STA_Info_EPG,
ID_STA_ResList_EPG,
ID_STA_PreDayIco_EPG,
ID_STA_LRIcon_EPG,
ID_STA_HelpBk_EPG,
ID_STA_DetailTitle_Epg,
ID_STA_TitleBk_EPG,
ID_STA_DetailBk_EPG,
ID_TIM_EPG,

//Epg数据保存提示框

ID_DLG_EpgInfo,
ID_TIM_EpgInfo,
ID_STAInfoTitle_EpgInfo,
ID_STAInfoText_EpgInfo,

//Epg预约节目的冲突提示框

ID_DLG_ConflictInfo,
ID_STATitle_ConflictInfo,
ID_STA_Line1_ConflictInfo,
ID_STA_Line2_ConflictInfo,
ID_STA_Line3_ConflictInfo,
ID_STA_Line4_ConflictInfo,
ID_STA_Line5_ConflictInfo,

//Epg中不能预约提示框

ID_DLG_EpgReserveInfo,
ID_STA_EpgReserveInfo,
ID_STA_Line1_EpgReserveInfo,
ID_TIM_EpgReserveInfo,

//预约节目列表

ID_DLG_ReserveList,
ID_ODC_ReserveList,
ID_STA_ReserveList_ReserveList,
ID_STA_ChannalName_ReserveList,
ID_STA_ProgramName_ReserveList,
ID_STA_PlayTime_ReserveList,
ID_STA_Note_ReserveList,
ID_STA_Title_ReserveList,
ID_STA_Notebk_ReserveList,
ID_LBX_ReserveList,
ID_STA_CancelPre_ReserveList,
ID_STA_Return_ReserveList,
ID_TIM_ReserveList,
ID_STA_SeqNum_ReserveList,
ID_STA_ReturnIco_ReserveList,

//预约节目列表提示框

ID_DLG_ReserveInfo,
ID_STA_ReserveInfo,
ID_STA_Line1_ReserveInfo,
ID_STA_Line2_ReserveInfo,

//预约节目列表的提示播放框

ID_DLG_TimeOut,
ID_ODC_TimeOut,
ID_TIM_TimeOut,
ID_STA_Line1_TimeOut,
ID_STA_Line2_TimeOut,
ID_STA_Line3_TimeOut,
ID_STA_Line4_TimeOut,
ID_STA_Line5_TimeOut,
ID_STA_Title_TimeOut,
ID_STA_Bk_TimeOut,

//娱乐游戏

ID_DLG_Game,
ID_STA_Time_Game,
ID_MNU_Game,
ID_STA_CardState_Game,
ID_VFM_Game,
ID_STA_Event1_Game,
ID_STA_Event2_Game,
ID_STA_ExitIco_Game,
ID_STA_ExitMenu_Game,
ID_STA_OkIco_Game,
ID_STA_OkMenu_Game,
ID_PBR_Epg_Game,

//俄罗斯方块

ID_DLG_Russia,
ID_STA_Time_Russia,
ID_STA_CardState_Russia,
ID_STA_Russia_Russia,
ID_STA_OKIco_Russia,
ID_STA_Start_Russia,
ID_VFM_Russia,
ID_ODC_Russia,
ID_TIM_Russia,
ID_STA_Up_Russia,
ID_STA_Donw_Russia,
ID_STA_Left_Russia,
ID_STA_Right_Russia,

//贪吃蛇

ID_DLG_Snake,
ID_STA_Time_Snake,
ID_STA_CardState_Snake,
ID_STA_Snake_Snake,
ID_STA_OKIco_Snake,
ID_STA_Start_Snake,
ID_VFM_Snake,
ID_ODC_Snake,
ID_TIM_Snake,

//推箱子

ID_DLG_Box,
ID_STA_Time_Box,
ID_STA_CardState_Box,
ID_STA_Box_Box,
ID_STA_Next_Box,
ID_STA_Pre_Box,
ID_STA_Cancel_Box,
ID_VFM_Box,
ID_ODC_Box,
ID_TIM_Box,

//系统设置

ID_DLG_SysSet,
ID_STA_Time_SysSet,
ID_MNU_SysSet,
ID_STA_CardState_SysSet,
ID_VFM_SysSet,
ID_STA_Event1_SysSet,
ID_STA_Event2_SysSet,
ID_STA_ExitIco_SysSet,
ID_STA_ExitMenu_SysSet,
ID_STA_OkIco_SysSet,
ID_STA_OkMenu_SysSet,
ID_PBR_Epg_SysSet,

//时区设置

ID_DLG_TimeZoneSet,
ID_STA_Time_TimeZoneSet,
ID_STA_Title_TimeZoneSet,
ID_CBX_TimeZoneTitle_TimeZoneSet,
ID_CBX_CurDateTitle_TimeZoneSet,
ID_CBX_CurTimeTitle_TimeZoneSet,
ID_CBX_TimeZone_TimeZoneSet,
ID_STA_CardState_TimeZoneSet,
ID_VFM_TimeZoneSet,
ID_STA_Event1_TimeZoneSet,
ID_STA_Event2_TimeZoneSet,
ID_STA_ExitIco_TimeZoneSet,
ID_STA_InNumber_TimeZoneSet,
ID_STA_ExitMenu_TimeZoneSet,
ID_CBX_CurDate_TimeZoneSet,
ID_CBX_CurTime_TimeZoneSet,
ID_PBR_Epg_TimeZoneSet,

//本机信息

ID_DLG_StbInfo,
ID_STA_Time_StbInfo,
ID_CBX_CardNum_StbInfo,
ID_CBX_SoftNum_StbInfo,
ID_CBX_HardNum_StbInfo,
ID_CBX_StbType_StbInfo,
ID_CBX_Chip_StbInfo,
ID_CBX_DataRadio_StbInfo,
ID_CBX_CaInfo_StbInfo,
ID_STA_Line2_StbInfo,
ID_STA_Line0_StbInfo,
ID_STA_Line1_StbInfo,
ID_STA_Line3_StbInfo,
ID_STA_Line4_StbInfo,
ID_STA_Line6_StbInfo,
ID_STA_Line5_StbInfo,
ID_STA_ExitIco_StbInfo,
ID_STA_ExitMenu_StbInfo,
ID_STA_StbInfo_StbInfo,
ID_CBX_FlashSize_StbInfo,
ID_CBX_SDRamSize_StbInfo,
ID_STA_Line7_StbInfo,
ID_STA_Line8_StbInfo,

//恢复出厂设置

ID_DLG_Default,
ID_STA_Time_Default,
ID_STA_Default_Default,
ID_STA_Attention_Default,
ID_STA_Line1_Default,
ID_STA_Line2_Default,
ID_STA_Line3_Default,
ID_TIM_Default,

//信息检测

ID_DLG_ProgState,
ID_STA_Title_ProgState,
ID_PBR_SigVoltage_ProgState,
ID_PBR_SigSNR_ProgState,
ID_STA_SigVoltage_ProgState,
ID_STA_SigSNR_ProgState,
ID_STA_Line12_ProgState,
ID_STA_Line11_ProgState,
ID_STA_Line10_ProgState,
ID_STA_Line9_ProgState,
ID_STA_Line8_ProgState,
ID_STA_Line7_ProgState,
ID_STA_Line6_ProgState,
ID_STA_Line5_ProgState,
ID_STA_Line4_ProgState,
ID_STA_Line3_ProgState,
ID_STA_Line2_ProgState,
ID_STA_Line1_ProgState,
ID_PBR_BER_ProgState,
ID_STA_BER_ProgState,
ID_STA_MAC_ProgState,
ID_STA_Line0_ProgState,
ID_STA_BK_ProgState,
ID_VFM_ProgState,
ID_TIM_ProgState,

//音视频设置

ID_DLG_AVSet,
ID_STA_AVSet_AVSet,
ID_CBX_TransparenceTitle_AvSet,
ID_CBX_TrackSetTitle_AVSet,
ID_CBX_DisplayFormatTitle_AVSet,
ID_CBX_TVModeTitle_AVSet,
ID_CBX_VideoOutTitle_AVSet,
ID_CBX_Transparence_AvSet,
ID_CBX_TrackSet_AVSet,
ID_CBX_DisplayFormat_AVSet,
ID_CBX_TVMode_AVSet,
ID_CBX_VideoOut_AVSet,
ID_STA_BK_AVSet,
ID_VFM_AVSet,

//系统升级(空中升级)

ID_DLG_SysUpdate,
ID_STA_Title_SysUpdate,
ID_CBX_PID_SysUpdate,
ID_CBX_TableID_SysUpdate,
ID_CBX_Fre_SysUpdate,
ID_CBX_SymbolRate_SysUpdate,
ID_CBX_QAMModeTitle_SysUpdate,
ID_TBX_PID_SysUpdate,
ID_TBX_TableID_SysUpdate,
ID_CBX_QAMMode_SysUpdate,
ID_STA_Line1_SysUpdate,
ID_STA_Line2_SysUpdate,
ID_STA_ExitIco_SysUpdate,
ID_STA_OKIco_SysUpdate,
ID_STA_ExitMenu_SysUpdate,
ID_STA_Ok_SysUpdate,
ID_TIM_SysUpdate,

//机顶盒密码修改

ID_DLG_PasswordSet,
ID_STA_Time_PasswordSet,
ID_STA_Title_PasswordSet,
ID_CBX_Old_PasswordSet,
ID_CBX_New_PasswordSet,
ID_CBX_Check_PasswordSet,
ID_TBX_Old_PasswordSet,
ID_TBX_New_PasswordSet,
ID_TBX_Check_PasswordSet,
ID_STA_CardState_PasswordSet,
ID_VFM_PasswordSet,
ID_STA_Event1_PasswordSet,
ID_STA_Event2_PasswordSet,
ID_STA_ExitIco_PasswordSet,
ID_STA_InNumber_PasswordSet,
ID_STA_ExitMenu_PasswordSet,
ID_PBR_Epg_PasswordSet,

//密码修改成功

ID_DLG_PasswordSetInfo,
ID_TIM_PasswordSetInfo,
ID_STA_Line1_PasswordSetInfo,
ID_STA_Title_PasswordSetInfo,

//语言设置

ID_DLG_LanguageSet,
ID_STA_Time_LanguageSet,
ID_STA_Title_LanguageSet,
ID_CBX_LangChoiceTitle_LanguageSet,
ID_CBX_LangChoice_LanguageSet,
ID_STA_CardState_LanguageSet,
ID_VFM_LanguageSet,
ID_STA_Event1_LanguageSet,
ID_STA_Event2_LanguageSet,
ID_STA_ExitIco_LanguageSet,
ID_STA_InNumber_LanguageSet,
ID_STA_ExitMenu_LanguageSet,
ID_PBR_Epg_LanguageSet,

//条件接收

ID_DLG_Ca,
ID_STA_Time_Ca,
ID_MNU_Ca,
ID_STA_CardState_Ca,
ID_VFM_Ca,
ID_STA_Event1_Ca,
ID_STA_Event2_Ca,
ID_STA_ExitIco_Ca,
ID_STA_ExitMenu_Ca,
ID_STA_OkIco_Ca,
ID_STA_OkMenu_Ca,
ID_PBR_Epg_Ca,

//pin 检查提示

ID_DLG_PinNote,
ID_TIM_PinNote,
ID_STA_Title_PinNote,
ID_STA_PinNote,

//卡状态

ID_DLG_CardState,
ID_TIM_CardState,
ID_STA_Title_CardState,
ID_STA_CardState,

//成人级设置

ID_DLG_Rating,
ID_STA_Time_Rating,
ID_STA_Title_Rating,
ID_CBX_Rating,
ID_CBX_Value_Rating,
ID_TBX_Rating,
ID_TBX_Value_Rating,
ID_STA_CardState_Rating,
ID_VFM_Rating,
ID_STA_Event1_Rating,
ID_STA_Event2_Rating,
ID_STA_ExitIco_Rating,
ID_STA_InNumber_Rating,
ID_STA_ExitMenu_Rating,
ID_STA_OkIco_Rating,
ID_STA_Ok_Rating,
ID_PBR_Epg_Rating,

//Ca卡密码修改

ID_DLG_PinSet,
ID_STA_Time_PinSet,
ID_STA_Title_PinSet,
ID_CBX_Old_PinSet,
ID_CBX_New_PinSet,
ID_CBX_Check_PinSet,
ID_TBX_Old_PinSet,
ID_TBX_New_PinSet,
ID_TBX_Check_PinSet,
ID_STA_CardState_PinSet,
ID_VFM_PinSet,
ID_STA_Event1_PinSet,
ID_STA_Event2_PinSet,
ID_STA_ExitIco_PinSet,
ID_STA_InNumber_PinSet,
ID_STA_ExitMenu_PinSet,
ID_STA_OkIco_PinSet,
ID_STA_Ok_PinSet,
ID_PBR_Epg_PinSet,

//设置工作时段

ID_DLG_WorkTime,
ID_STA_Time_WorkTime,
ID_STA_Title_WorkTime,
ID_CBX_PIN_WorkTime,
ID_CBX_StartTime_WorkTime,
ID_CBX_EndTime_WorkTime,
ID_TBX_PIN_WorkTime,
ID_ODC_StartTime_WorkTime,
ID_ODC_EndTime_WorkTime,
ID_STA_CardState_WorkTime,
ID_VFM_WorkTime,
ID_STA_Event1_WorkTime,
ID_STA_Event2_WorkTime,
ID_STA_ExitIco_WorkTime,
ID_STA_InNumber_WorkTime,
ID_STA_ExitMenu_WorkTime,
ID_STA_OkIco_WorkTime,
ID_STA_Ok_WorkTime,
ID_PBR_Epg_WorkTime,

//电子邮件

ID_DLG_Mail,
ID_STA_Status_Mail,
ID_STA_SeqNum_Mail,
ID_STA_Time_Mail,
ID_STA_Title_Mail,
ID_STA_MailInfo_Mail,
ID_STA_OKIco_Mail,
ID_STA_ExitIco_Mail,
ID_STA_Read_Mail,
ID_STA_DelCurrent_Mail,
ID_STA_DelAll_Mail,
ID_STA_ExitMenu_Mail,
ID_STA_Note_Mail,
ID_STA_Notetitle_Mail,
ID_STA_NoteBk_Mail,
ID_SBR_Mail,
ID_LBP_Mail,
ID_STA_MailNum_Mail,
ID_STA_MaxNum_Mail,
ID_TIM_Mail,
ID_STA_Level_Mail,
ID_STA_Time1_Mail,

//智能卡基本信息

ID_DLG_ICInfo,
ID_STA_Time_ICInfo,
ID_STA_Menu_ICInfo,
ID_STA_ExitIco_ICInfo,
ID_STA_Exit_ICInfo,
ID_STA_Line1_ICInfo,
ID_STA_Line2_ICInfo,
ID_STA_Line3_ICInfo,
ID_STA_Line4_ICInfo,
ID_STA_Line5_ICInfo,
ID_STA_Line6_ICInfo,
ID_STA_Line7_ICInfo,
ID_STA_Line8_ICInfo,
ID_STA_Line9_ICInfo,
ID_STA_Line10_ICInfo,
ID_STA_Line11_ICInfo,
ID_STA_Line12_ICInfo,
ID_STA_Line13_ICInfo,

//获取所有运行商

ID_DLG_GetServicer,
ID_STA_Time_GetServicer,
ID_STA_Menu_GetServicer,
ID_STA_OKIco_GetServicer,
ID_STA_OK_GetServicer,
ID_STA_ExitIco_GetServicer,
ID_STA_Exit_GetServicer,
ID_STA_Note_GetServicer,
ID_STA_Line1_GetServicer,
ID_STA_NoteBk_GetServicer,
ID_LBX_GetServicer,
ID_TIM_GetServicer,
ID_STA_Status_GetServicer,

//电子钱包信息

ID_DLG_ePurse,
ID_STA_Time_ePurse,
ID_STA_Menu_ePurse,
ID_STA_Text_ePurse,
ID_STA_Title_ePurse,
ID_STA_TextBk_ePurse,
ID_STA_ExitIco_ePurse,
ID_STA_Exit_ePurse,
ID_STA_Line0_ePurse,
ID_STA_Line1_ePurse,
ID_STA_Line2_ePurse,
ID_STA_Line3_ePurse,
ID_STA_Line4_ePurse,
ID_STA_Line5_ePurse,
ID_STA_Line6_ePurse,
ID_STA_Line7_ePurse,
ID_STA_Line8_ePurse,
ID_STA_Line9_ePurse,

//查询授权信息

ID_DLG_EntitleInfo,
ID_STA_Time_EntitleInfo,
ID_STA_Menu_EntitleInfo,
ID_STA_Text_EntitleInfo,
ID_STA_Title_EntitleInfo,
ID_STA_TextBk_EntitleInfo,
ID_STA_UD_EntitleInfo,
ID_STA_ExitIco_EntitleInfo,
ID_STA_Exit_EntitleInfo,
ID_STA_Line0_EntitleInfo,
ID_STA_Line1_EntitleInfo,
ID_STA_Line2_EntitleInfo,
ID_STA_Line3_EntitleInfo,
ID_STA_Line4_EntitleInfo,
ID_STA_Line5_EntitleInfo,
ID_STA_Line6_EntitleInfo,
ID_STA_Line7_EntitleInfo,
ID_STA_Line8_EntitleInfo,
ID_STA_Line9_EntitleInfo,

//查询IPP信息

ID_DLG_IPPInfo,
ID_STA_Time_IPPInfo,
ID_STA_Menu_IPPInfo,
ID_STA_Text_IPPInfo,
ID_STA_Title_IPPInfo,
ID_STA_TextBk_IPPInfo,
ID_STA_UD_IPPInfo,
ID_STA_ExitIco_IPPInfo,
ID_STA_Exit_IPPInfo,
ID_STA_Line0_IPPInfo,
ID_STA_Line1_IPPInfo,
ID_STA_Line2_IPPInfo,
ID_STA_Line3_IPPInfo,
ID_STA_Line4_IPPInfo,
ID_STA_Line5_IPPInfo,
ID_STA_Line6_IPPInfo,
ID_STA_Line7_IPPInfo,
ID_STA_Line8_IPPInfo,
ID_STA_Line9_IPPInfo,

//子母卡管理

ID_DLG_MasterSlaveManage,
ID_STA_MasterSlaveManage,
ID_STA_OKIco_MasterSlaveManage,
ID_STA_OK_MasterSlaveManage,
ID_STA_ExitIco_MasterSlaveManage,
ID_STA_Exit_MasterSlaveManage,
ID_STA_Line1_MasterSlaveManage,
ID_STA_Title_MasterSlaveManage,
ID_STA_Note_MasterSlaveManage,
ID_STA_NoteBk_MasterSlaveManage,
ID_LBX_MasterSlaveManage,
ID_STA_Time_MasterSlaveManage,

//配对子母卡

ID_DLG_MasterSlave,
ID_STA_MasterSlave,
ID_STA_Msg_MasterSlave,
ID_STA_OKIco_MasterSlave,
ID_STA_OK_MasterSlave,
ID_STA_ExitIco_MasterSlave,
ID_STA_Exit_MasterSlave,
ID_STA_Line1_MasterSlave,
ID_STA_Time_MasterSlave,
ID_STA_OKIco1_MasterSlave,

//请求喂养子母卡

ID_DLG_RequestFeed,
ID_STA_RequestFeed,
ID_STA_Line1_RequestFeed,
ID_STA_OKIco_RequestFeed,
ID_STA_ExitIco_RequestFeed,

//查询用户特征

ID_DLG_ACList,
ID_STA_Servicer_ACList,
ID_STA_Line1_ACList,
ID_STA_Line2_ACList,
ID_STA_Line3_ACList,
ID_STA_Line4_ACList,
ID_STA_Line5_ACList,
ID_STA_Line6_ACList,
ID_STA_Line7_ACList,
ID_STA_Line8_ACList,
ID_STA_Line9_ACList,
ID_STA_ExitIco_ACList,
ID_STA_Exit_ACList,
ID_STA_Text_ACList,
ID_STA_Title_ACList,
ID_STA_TextBk_ACList,
ID_STA_Time_ACList,

//查询反授权确认码

ID_DLG_DetitleChkNums,
ID_STA_ReserveList_DetitleChkNums,
ID_STA_ChannalName_DetitleChkNums,
ID_STA_note_DetitleChkNums,
ID_STA_notetitle_DetitleChkNums,
ID_STA_notebk_DetitleChkNums,
ID_LBX_DetitleChkNums,
ID_STA_CancelPre_DetitleChkNums,
ID_STA_DeleteAll_DetitleChkNums,
ID_STA_ExitIco_DetitleChkNums,
ID_STA_ExitMenu_DetitleChkNums,
ID_STA_Time_DetitleChkNums,

//删除反授权确认码

ID_DLG_DelDetitle,
ID_STA_DelDetitle,
ID_STA_Line1_DelDetitle,
ID_STA_Line2_DelDetitle,

//拔卡

ID_DLG_CardOut,
ID_ODC_CardOut,
ID_TIM_CardOut,

//喂养子母卡

ID_DLG_Feeding,
ID_STA_Text_Feeding,
ID_STA_Title_Feeding,
ID_STA_TextBk_Feeding,
ID_TIM_Feeding,

//正在获取区域锁定信息(不响应任何按键)

ID_DLG_AreaLockInfo,
ID_STA_AreaLockInfo,
ID_STA_bk_AreaLockInfo,
ID_VFM_AreaLockInfo,

//单频点设置

ID_DLG_SingleSlot,
ID_STA_SingleSlot,
ID_TBX_SingleSlot,
ID_STA_OKIco_SingleSlot,
ID_STA_OK_SingleSlot,
ID_STA_ExitIco_SingleSlot,
ID_STA_ExitMenu_SingleSlot,
ID_STA_Title_SingleSlot,

//图片浏览状态

ID_DLG_PictureShow,
ID_TIM_PictureShow,

//特效菜单

ID_DLG_Effects,
ID_STA_CardState_Effects,
ID_VFM_Effects,
ID_MNU_Effects,
ID_STA_event1_Effects,
ID_STA_event2_Effects,
ID_STA_OkIco_Effects,
ID_STA_EnterMenu_Effects,
ID_STA_ExitIco_Effects,
ID_STA_ExitMenu_Effects,
ID_STA_Time_Effects,
ID_PBR_Epg_Effects,

//特效提示框

ID_DLG_EffectsInfo,
ID_STA_Line1_EffectsInfo,
ID_STA_Menu_EffectsInfo,
ID_TIM_EffectsInfo,

//删除当前邮件

ID_DLG_DelCurrent,
ID_STA_DelCurrent,
ID_STA_Line1_DelCurrent,
ID_STA_Line2_DelCurrent,

//读邮件

ID_DLG_ReadMail,
ID_STA_MailInfo_ReadMail,
ID_STA_ExitIco_ReadMail,
ID_STA_ExitMenu_ReadMail,
ID_STA_Page_ReadMail,
ID_EDT_ReadMail,
ID_STA_Line1_ReadMail,
ID_STA_Line2_ReadMail,
ID_STA_Line3_ReadMail,
ID_STA_2_ReadMail,
ID_STA_1_ReadMail,
ID_STA_Time_ReadMail,

//手动选时录制

ID_DLG_ManualRec,
ID_LBP_Prog_ManualRec,
ID_SBR_Prog_ManualRec,
ID_LBP_Week_ManualRec,
ID_TIM_ManualRec,
ID_CBX_StartTime_ManualRec,
ID_CBX_EndTime_ManualRec,
ID_ODC_StartTime_ManualRec,
ID_ODC_EndTime_ManualRec,
ID_STA_ProgTitle_ManualRec,
ID_STA_WeekTitle_ManualRec,
ID_STA_Title_ManualRec,

//时移状态
ID_DLG_TimeShift,
ID_STA_TimeShift_StartTime,
ID_PBR_Record_TimeShift,
ID_STA_TimeShift_EndTime,
ID_VOI_TimeShift,
ID_STA_PauseStr_TimeShift,
ID_STA_PlayStr_TimeShift,
ID_STA_PauseInfoBK_TimeShift,
ID_ODC_NowTime_TimeShift,
ID_TIM_TimeShift,
ID_ODC_JumpTO_TimeShift,
ID_STA_JumpBarBk_TimeShift,
ID_STA_TimeJumpToBk_TimeShift,
ID_STA_HelpTitle_TimeShift,
ID_STA_HelpLine1_TimeShift,
ID_STA_HelpLine2_TimeShift,
ID_STA_HelpLine3_TimeShift,
ID_STA_HelpLine4_TimeShift,
ID_STA_HelpLine5_TimeShift,
ID_STA_HelpLine6_TimeShift,
ID_STA_HelpLine7_TimeShift,
ID_STA_HelpBk_TimeShift,
ID_STA_SpeedNumX_TimeShift,
ID_STA_SpeedNum1_TimeShift,
ID_STA_SpeedNum2_TimeShift,
ID_STA_SpeedIcon_TimeShift,
ID_STA_FullScreenBk_TimeShift,
ID_TIM_BrushScreen_TimeShift,

//Nvod

ID_DLG_Nvod,
ID_STA_LR_Nvod,
ID_STA_InfoIco_Nvod,
ID_STA_EventDetail_Nvod,
ID_STA_ReserveList_Nvod,
ID_LBP_EventList_Nvod,
ID_SBR_EventList_Nvod,
ID_LBP_EventPlayTime_Nvod,
ID_SBR_EventPlayTime_Nvod,
ID_STA_Title_Nvod,
ID_STA_CardState_Nvod,
ID_VFM_Nvod,
ID_STA_Time_Nvod,
ID_STA_EventListTitle_Nvod,
ID_STA_EventPlayTimeTitle_Nvod,
ID_EDT_Nvod,
ID_TIM_Nvod,
ID_STA_MovieTimeLeng_Nvod,
ID_STA_MovieName_Nvod,
ID_STA_MovieTimeLengContent_Nvod,
ID_STA_MovieNameContent_Nvod,

//NvodPlay全屏播放

ID_DLG_NvodPlay,
ID_VOI_NvodPlay,
ID_CHN_NvodPlay,
ID_STAMute_NvodPlay,
ID_STAMuteBk_NvodPlay,
ID_STA_ChnInfoTitle_NvodPlay,
ID_STA_Line1_NvodPlay,
ID_STA_Line2_NvodPlay,
ID_STA_Line3_NvodPlay,
ID_STA_Line4_NvodPlay,
ID_PBR_NvodPlay,
ID_STA_PbrText_NvodPlay,
ID_STA_Line5_NvodPlay,
ID_STA_Line6_NvodPlay,
ID_STA_Line7_NvodPlay,
ID_STA_Line8_NvodPlay,
ID_STA_Line9_NvodPlay,
ID_STA_ChnInfoBk_NvodPlay,
ID_STA_Text_NvodPlay,
ID_STA_Title_NvodPlay,
ID_STA_TextBk_NvodPlay,
ID_STA_Time_NvodPlay,
ID_STA_EventDetai_Title_NvodPlay,
ID_STA_EventDetail_MovieName_NvodPlay,
ID_EDT_NvodPlay,
ID_STA_EventDetailBk_NvodPlay,
ID_STA_FullTrans_NvodPlay,
ID_VFM_NvodPlay,
ID_TIM_NvodPlay,

//NvodPlay全屏播放退出提示框

ID_DLG_NvodPlayInfo,
ID_STA_Line1_NvodPlayInfo,
ID_STA_Line2_NvodPlayInfo,
ID_STA_Line3_NvodPlayInfo,
ID_STA_Bk_NvodPlayInfo,
ID_VFM_NvodPlayInfo,

//进入Nvod时等待界面

ID_DLG_NvodWait,
ID_STA_Line1_NvodWait,
ID_STA_Line2_NvodWait,
ID_PBR_NvodWait,
ID_STA_Bk_NvodWait,
ID_VFM_NvodWait,
ID_TIM_NvodWait,

//互动设置

ID_DLG_NetSet,
ID_STA_Time_NetSet,
ID_STA_Title_NetSet,
ID_CBX_SwitchItemTitle_NetSet,
ID_CBX_AutoIPTitle_NetSet,
ID_CBX_IPAddressTitle_NetSet,
ID_CBX_SubnetworkTitle_NetSet,
ID_CBX_GatewayIPTitle_NetSet,
ID_CBX_AutoDNSTitle_NetSet,
ID_CBX_FirstChoseDNSTitle_NetSet,
ID_CBX_ReserveDNSTitle_NetSet,
ID_CBX_FirstpageAddrTitle_NetSet,
ID_CBX_SwitchItem_NetSet,
ID_CBX_AutoIP_NetSet,
ID_CBX_AutoDNS_NetSet,
ID_STA_CardState_NetSet,
ID_VFM_NetSet,
ID_STA_Event1_NetSet,
ID_STA_Event2_NetSet,
ID_STA_InNumber_NetSet,
ID_STA_ExitIco_NetSet,
ID_STA_ExitMenu_NetSet,
ID_ODC_IPAddress_NetSet,
ID_ODC_Subnetwork_NetSet,
ID_ODC_GatewayIP_NetSet,
ID_ODC_FirstChoseDNS_NetSet,
ID_ODC_ReserveDNS_NetSet,
ID_ODC_FirstpageAddr_NetSet,
ID_PBR_Epg_NetSet,

//保存IP设置对话框

ID_DLG_Preserve_NetSet,
ID_STA_PreserveTitle,
ID_STA_Line1_PreserveTitle,
ID_STA_Line2_PreserveTitle,

//保存IP设置信息提示

ID_DLG_Prompt_NetSet,
ID_STA_Prompt,
ID_STA_Line1_Prompt,
ID_TIM_Prompt,

//Pvr播放列表

ID_DLG_PvrList,
ID_STA_AllFile_PvrList,
ID_STA_FileListBk_PvrList,
ID_STA_Time_PvrList,
ID_LBP_FileList_PvrList,
ID_SBR_FileList_PvrList,
ID_STA_CreateDate_PvrList,
ID_STA_FileSize_PvrList,
ID_STA_Line2_PvrList,
ID_STA_Line1_PvrList,
ID_STA_Enter_PvrList,
ID_STA_Return_PvrList,
ID_VFM_PvrList,
ID_STA_FileList_PvrList,

//Pvr全屏播放

ID_DLG_PvrFullScreen,
ID_STA_PauseBtn_PvrFullScreen,
ID_STA_PlayBtn_PvrFullScreen,
ID_STA_BackwordBtn_PvrFullScreen,
ID_STA_ForwordBtn_PvrFullScreen,
ID_STA_TimerBtn_PvrFullScreen,
ID_PBR_PvrFullScreen,
ID_STA_PvrBarBk_PvrFullScreen,
ID_STA_PvrPlayerBarBk_PvrFullScreen,
ID_VOI_PvrFullScreen,
ID_STA_SpeedNumX_PvrFullScreen,
ID_STA_SpeedNum1_PvrFullScreen,
ID_STA_SpeedNum2_PvrFullScreen,
ID_VFM_PvrFullScreen,
ID_STA_FullScreenBK_PvrFullScreen,
ID_TIM_PvrFullScreen,

//机卡配对

ID_DLG_CardPair,
ID_STA_CardPair,
ID_STA_ExitIco_CardPair,
ID_STA_Exit_CardPair,
ID_STA_Line1_StbID,
ID_STA_Line2_StbID,
ID_STA_Line3_StbID,
ID_STA_Line4_StbID,
ID_STA_Line5_StbID,
ID_STA_Msg_CardPair,
ID_STA_Line1_CardPair,
ID_STA_Time_CardPair,

//工厂菜单

ID_DLG_FactoryMenu,
ID_STA_Title_FactoryMenu,
ID_CBX_Led_FactoryMenu,
ID_CBX_ProResume_FactoryMenu,
ID_CBX_E2P_FactoryMenu,
ID_CBX_SN_FactoryMenu,
ID_CBX_LedDetect_Factory,
ID_CBX_E2p_Factory,
ID_CBX_ProResume_Factory,
ID_TBX_InputSN_Factory,
ID_STA_ExitIco_Factory,
ID_STA_ExitMenu_Factory,
ID_TIM_SnInput_Factory,

//

ID_DLG_FULLTOTVOD,
ID_ODC_JUMPBAR,
ID_STA_PP_EXIT_LINE1,
ID_STA_PP_EXIT_LINE2,
ID_STA_PP_EXIT_LINE3,
ID_STA_PP_EXIT,
ID_ODC_BPZHUN,
ID_STA_BAK_BPZHUN,
ID_TIM_BPZHUN,
ID_STA_BPLOGO,
ID_STA_PP_PAUSE,
ID_STA_PP_CONTINUE,
ID_STA_PP_CONTINUE_2,
ID_STA_TVOD_MUTE,
ID_STA_PP_PAUSE_2,
ID_STA_PP_PLAYTIME,
ID_STA_INBP,
ID_STA_INFOBP,
ID_STA_PP,
ID_ODC_FAST,
ID_STA_ERROR_LINE1,
ID_STA_ERROR_LINE2,
ID_VOI_TVOD,
ID_STA_VOI_TVOD,
ID_STA_TVOD_MUTE_BAK,
ID_STA_TVOD_CHECKNET,
ID_STA_PLAYCHN,
ID_TIM_CLEANSCREEN,
ID_STA_TVOD_HELP,
ID_STA_TVOD_HELP_LINE1,
ID_STA_TVOD_HELP_LINE2,
ID_STA_TVOD_HELP_LINE3,
ID_STA_TVOD_HELP_LINE4,
ID_STA_TVOD_HELP_LINE5,
ID_STA_TVOD_HELP_LINE6,
ID_PBR_SigVoltage_FULLTOTVOD,
ID_PBR_SigSNR_FULLTOTVOD,
ID_STA_SigVoltage_FULLTOTVOD,
ID_STA_SigSNR_FULLTOTVOD,
ID_STA_Line12_FULLTOTVOD,
ID_STA_Line11_FULLTOTVOD,
ID_STA_Line10_FULLTOTVOD,
ID_PBR_BER_FULLTOTVOD,
ID_STA_BER_FULLTOTVOD,
ID_STA_TVOD_HELP_BK,
ID_STA_FullScreenBk_TVOD,
ID_TIM_TVOD,
ID_TIM_SignalCheck_TVOD,



ID_DLG_VOD,
ID_STA_VOD_PP_EXIT_LINE1,
ID_STA_VOD_PP_EXIT_LINE2,
ID_STA_THANKS,
ID_STA_THANKS_BAK,
ID_STA_VOD_PP_EXIT_LINE3,
ID_STA_VOD_PP_EXIT,
ID_STA_VOD_CHECKNET,
ID_STA_VOD_CHECKNET_BAK,
ID_ODC_VOD_JUMPTO,
ID_ODC_VOD_JUMPBAR,
ID_PBR_VOD_JUMPBAR,
ID_STA_VOD_JUMPBAR,
ID_STA_VOD_JUMPTO,
ID_TIM_VOD,
ID_VOI_VOD,
ID_STA_VOD_MUTE,
ID_STA_VOD_MUTE_BAK,
ID_STA_VOD_EXIT_PAUSE,
ID_STA_VOD_EXIT_CONTINUE,
ID_STA_VOD_EXIT_BAK,
ID_STA_VOD_HELP_BK,
ID_STA_VOD_HELP,
ID_STA_VOD_HELP_LINE1,
ID_STA_VOD_HELP_LINE2,
ID_STA_VOD_HELP_LINE3,
ID_STA_VOD_HELP_LINE4,
ID_STA_VOD_HELP_LINE5,
ID_STA_VOD_HELP_LINE6,



ID_DLG_INFOCONNECT,
ID_STA_INFOCONNECT,
ID_STA_INFOCONNECT_BAK,
ID_TIM_INFO_CONNECT,

//双向开机

ID_DLG_VOD_FIRST_STATE,
ID_TIM_VOD_FIRST,
ID_STA_VOD_FIRST_INFO,
ID_STA_VOD_FIRST_INFO_BAK,

//文件浏览

ID_DLG_UsbManager,
ID_STA_FileScan_UsbManager,
ID_STA_Time_UsbManager,
ID_STA_Directory_UsbManager,
ID_LBP_FileList_UsbManager,
ID_SBR_FileList_UsbManager,
ID_STA_CreateDate_UsbManager,
ID_STA_FileSize_UsbManager,
ID_STA_Line2_UsbManager,
ID_STA_Line1_UsbManager,
ID_STA_Delete_UsbManager,
ID_STA_Enter_UsbManager,
ID_STA_Return_UsbManager,
ID_VFM_UsbManager,
ID_STA_FileListBK_UsbManager,

//区域ID设置

ID_DLG_RegionSet,
ID_STA_Time_RegionSet,
ID_STA_Title_RegionSet,
ID_CBX_AutoRegionTitle_RegionSet,
ID_CBX_RegionIDTitle_RegionSet,
ID_CBX_AutoRegion_RegionSet,
ID_TBX__RegionID_RegionSet,
ID_STA_CardState_RegionSet,
ID_VFM_RegionSet,
ID_STA_Event1_RegionSet,
ID_STA_Event2_RegionSet,
ID_STA_ExitIco_RegionSet,
ID_STA_InNumber_RegionSet,
ID_STA_ExitMenu_RegionSet,
ID_PBR_Epg_RegionSet,

//stbid setting

ID_DLG_StbIDSetting,
ID_STA_Title_StbIDSetting,
ID_CBX_AreaIndicatorCode_StbIDSetting,
ID_CBX_ManufactureCode_StbIDSetting,
ID_CBX_StbFactoryIndicator_StbIDSetting,
ID_CBX_StbType_StbIDSetting,
ID_CBX_HwVersion_StbIDSetting,
ID_CBX_StbIndicatorType_StbIDSetting,
ID_CBX_MacAddress_StbIDSetting,
ID_STA_ExitIco_StbIDSetting,
ID_STA_ExitMenu_StbIDSetting,
ID_STA_AreaIndicatorCode,
ID_STA_StbType,
ID_STA_ManufactureCode,
ID_STA_HwVersion,
ID_STA_StbIndicatorType,
ID_STA_MacAddress,
ID_STA_StbFactoryIndicator,
ID_TIM_StbIDSetting,

//使用操作指南

ID_DLG_OperationGuide,
ID_STA_Title_OperationGuide,
ID_STA_Time_OperationGuide,
ID_STA_KeyValue_OperationGuide,
ID_STA_Name_OperationGuide,
ID_STA_Illuminate_OperationGuide,
ID_STA_ReturnIco_OperationGuide,
ID_STA_ReturnStr_OperationGuide,
ID_STA_ScanIco_OperationGuide,
ID_SBR_OperationGuide,
ID_ODC_OperationGuide,

//输出设置

ID_DLG_OutPutSet,
ID_STA_Title_OutPutSet,
ID_STA_Time_OutPutSet,
ID_CBX_TVModeTitle_OutPutSet,
ID_CBX_VideoOutTitle_OutPutSet,
ID_CBX_TVMode_OutPutSet,
ID_CBX_VideoOut_OutPutSet,
ID_STA_CardState_OutPutSet,
ID_VFM_OutPutSet,
ID_STA_OkIco_OutPutSet,
ID_STA_OkStr_OutPutSet,
ID_STA_ReturnIco_OutPutSet,
ID_STA_ReturnStr_OutPutSet,
ID_STA_SwitchLR_OutPutSet,
ID_STA_Event1_OutPutSet,
ID_STA_Event2_OutPutSet,
ID_PBR_Epg_OutPutSet,

//显示设置

ID_DLG_DisplaySet,
ID_STA_Title_DisplaySet,
ID_STA_Time_DisplaySet,
ID_CBX_TVModeTitle_DisplaySet,
ID_CBX_VideoOutTitle_DisplaySet,
ID_CBX_TVMode_DisplaySet,
ID_CBX_VideoOut_DisplaySet,
ID_CBX_TransTitle_DisplaySet,
ID_CBX_DisplayScaleTitle_DisplaySet,
ID_CBX_Trans_DisplaySet,
ID_CBX_DisplayScale_DisplaySet,
ID_STA_CardState_DisplaySet,
ID_VFM_DisplaySet,
ID_STA_OkIco_DisplaySet,
ID_STA_OkStr_DisplaySet,
ID_STA_ReturnIco_DisplaySet,
ID_STA_ReturnStr_DisplaySet,
ID_STA_SwitchLR_DisplaySet,
ID_STA_Event1_DisplaySet,
ID_STA_Event2_DisplaySet,
ID_CBX_InfoTime_DisplaySet,
ID_CBX_InfoTimeTitle_DisplaySet,
ID_PBR_Epg_DisplaySet,
ID_CBX_VolumeSaveTitle_DisplaySet,
ID_CBX_VolumeSave_DisplaySet,

//频道设置

ID_DLG_ChannelSet,
ID_STA_Title_ChannelSet,
ID_STA_Time_ChannelSet,
ID_CBX_TrackTitle_ChannelSet,
ID_CBX_OffSetTitle_ChannelSet,
ID_CBX_Track_ChannelSet,
ID_CBX_OffSet_ChannelSet,
ID_STA_CardState_ChannelSet,
ID_VFM_ChannelSet,
ID_STA_OkIco_ChannelSet,
ID_STA_OkStr_ChannelSet,
ID_STA_ReturnIco_ChannelSet,
ID_STA_ReturnStr_ChannelSet,
ID_STA_SwitchLR_ChannelSet,
ID_STA_Event1_ChannelSet,
ID_STA_Event2_ChannelSet,
ID_CBX_ChannelSkip_ChannelSet,
ID_CBX_ChannelSkipTitle_ChannelSet,
ID_CBX_ChannelFavTitle_ChannelSet,
ID_CBX_ChannelFav_ChannelSet,
ID_PBR_Epg_ChannelSet,

//频道设置保存提示框

ID_DLG_ChannelSetInfo,
ID_STA_Title_ChannleSetInfo,
ID_STA_Content_ChannelSetInfo,
ID_TIM_ChannelSetInfo,

//父母控制

ID_DLG_ParentControl,
ID_STA_Title_ParentControl,
ID_STA_Time_ParentControl,
ID_CBX_MenuTitle_ParentControl,
ID_CBX_ChannelTitle_ParentControl,
ID_CBX_MenuLockSet_ParentControl,
ID_CBX_ChannelLockSet_ParentControl,
ID_STA_CardState_ParentControl,
ID_VFM_ParentControl,
ID_STA_OkIco_ParentControl,
ID_STA_OkStr_ParentControl,
ID_STA_ReturnIco_ParentControl,
ID_STA_ReturnStr_ParentControl,
ID_STA_SwitchLR_ParentControl,
ID_STA_Event1_ParentControl,
ID_STA_Event2_ParentControl,
ID_CBX_BootLockSet_ParentControl,
ID_CBX_BootTitle_ParentControl,
ID_PBR_Epg_ParentControl,

//信号检测

ID_DLG_SignalCheck,
ID_STA_Title_SignalCheck,
ID_LBP_SignalCheck,
ID_STA_Strong_SignalCheck,
ID_STA_Quality_SignalCheck,
ID_STA_BE_SignalCheck,
ID_STA_Illuminate_SignalCheck,
ID_PBR_Voltage_SignalCheck,
ID_PBR_SNR_SignalCheck,
ID_PBR_CER_SignalCheck,
ID_STA_StrengthNum_SignalCheck,
ID_STA_SnrNum_SignalCheck,
ID_STA_BerNum_SignalCheck,
ID_SBR_SignalCheck,
ID_STA_Bk_SignalCheck,
ID_TIM_SignalCheck,

//开机锁

ID_DLG_StartUpLock,
ID_ODC_StartUpLock,
ID_STA_Title_StartUpLock,
ID_STA_InfoStr_StartUpLock,
ID_TIM_StartUpLock,



ID_DLG_ChnEdit,
ID_STA_Title_ChnEdit,
ID_STA_Time_ChnEdit,
ID_LBP_ChnList_ChnEdit,
ID_SBR_ChnEdit,
ID_STA_FavTitle_ChnEdit,
ID_STA_SortName_ChnEdit,
ID_STA_MoveTitle_ChnEdit,
ID_STA_SkipTitle_ChnEdit,
ID_STA_LockTitle_ChnEdit,
ID_STA_Ico1_ChnEdit,
ID_STA_Ico2_ChnEdit,
ID_STA_Text1_ChnEdit,
ID_STA_Text2_ChnEdit,
ID_STA_Ico3_ChnEdit,
ID_STA_Text3_ChnEdit,
ID_STA_Ico4_ChnEdit,
ID_STA_Text4_ChnEdit,
ID_STA_Ico5_ChnEdit,
ID_STA_Text5_ChnEdit,
ID_STA_Text6_ChnEdit,
ID_TIM_ChnEdit,



ID_DLG_FacMenu,
ID_STA_CardState_FacMenu,
ID_VFM_FacMenu,
ID_MNU_FacMenu,
ID_STA_event1_FacMenu,
ID_STA_event2_FacMenu,
ID_STA_OkIco_FacMenu,
ID_STA_EnterMenu_FacMenu,
ID_STA_ExitIco_FacMenu,
ID_STA_ExitMenu_FacMenu,
ID_STA_Time_FacMenu,
ID_PBR_Epg_FacMenu,

//频点设置

ID_DLG_FreqSet,
ID_STA_Title_FreqSet,
ID_STA_Time_FreqSet,
ID_CBX_MainFreqTitle_FreqSet,
ID_CBX_ADFreqTitle_FreqSet,
ID_STA_CardState_FreqSet,
ID_VFM_FreqSet,
ID_STA_ReturnIco_FreqSet,
ID_STA_ReturnStr_FreqSet,
ID_STA_SwitchLR_FreqSet,
ID_STA_Event1_FreqSet,
ID_STA_Event2_FreqSet,
ID_CBX_NvodFreqTitle_FreqSet,
ID_CBX_BroadCastFreq_FreqSet,
ID_PBR_Epg_FreqSet,
ID_CBX_StockFreqTitle_FreqSet,
ID_TBX_MainFreq_FreqSet,
ID_TBX_AdFreq_FreqSet,
ID_TBX_NvodFreq_FreqSet,
ID_TBX_BroadFreq_FreqSet,
ID_TBX_StockFreq_FreqSet,

//序列号

ID_DLG_Sequence,
ID_STA_Title_Sequence,
ID_STA_Time_Sequence,
ID_CBX_ManufactureTitle_Sequence,
ID_CBX_StbTypeTitle_Sequence,
ID_STA_CardState_Sequence,
ID_VFM_Sequence,
ID_STA_OkStr_Sequence,
ID_STA_ReturnIco_Sequence,
ID_STA_Event1_Sequence,
ID_STA_Event2_Sequence,
ID_CBX_ProductyearTitle_Sequence,
ID_CBX_ProductweekTitle_Sequence,
ID_PBR_Epg_Sequence,
ID_CBX_SequenceTitle_Sequence,
ID_TBX_Manufacture_Sequence,
ID_TBX_StbType_Sequence,
ID_TBX_Productyear_Sequence,
ID_TBX_Productweek_Sequence,
ID_TBX_Sequence_Sequence,
ID_STA_Info_Sequence,

//空中升级

ID_DLG_OTA,
ID_STA_Title_OTA,
ID_STA_Time_OTA,
ID_CBX_PIDTitle_OTA,
ID_STA_CardState_OTA,
ID_VFM_OTA,
ID_STA_OkIco_OTA,
ID_STA_OkStr_OTA,
ID_STA_ReturnIco_OTA,
ID_STA_ReturnStr_OTA,
ID_STA_Event1_OTA,
ID_STA_Event2_OTA,
ID_CBX_FreqTitle_OTA,
ID_CBX_SymbTitle_OTA,
ID_PBR_Epg_OTA,
ID_CBX_QAMModeTitle_OTA,
ID_CBX_QAMMode_OTA,
ID_TBX_PID_OTA,
ID_TBX_Freq_OTA,
ID_TBX_Symb_OTA,
ID_TIM_OTA,

//串口写序列号

ID_DLG_ComSequence,
ID_STA_Title_ComSequence,
ID_STA_Time_ComSequence,
ID_CBX_DetectCardTitle_ComSequence,
ID_CBX_DetectE2Title_ComSequence,
ID_CBX_DetectCard_ComSequence,
ID_CBX_DetectE2_ComSequence,
ID_STA_CardState_ComSequence,
ID_VFM_ComSequence,
ID_STA_ReturnIco_ComSequence,
ID_STA_ReturnStr_ComSequence,
ID_STA_Event1_ComSequence,
ID_STA_Event2_ComSequence,
ID_CBX_DetectCom_ComSequence,
ID_CBX_DetectComTitle_ComSequence,
ID_PBR_Epg_ComSequence,
ID_STA_ComInfo_ComSequence,
ID_TIM_ComSequence,
ID_STA_ComInfo_ComSTBID,
ID_CBX_EthSetTitle_ComSequence,
ID_CBX_EthSet_ComSequence,

//订购/退订IPP节目

ID_DLG_BookUnbook,
ID_STA_BookUnbook,
ID_STA_TextTitle_BookUnbook,
ID_STA_Text_BookUnbook,
ID_STA_TextBk_BookUnbook,
ID_STA_Prog_BookUnbook,
ID_LBP_Ipp_BookUnbook,
ID_STA_Line1_BookUnbook,
ID_STA_Line2_BookUnbook,
ID_STA_Line3_BookUnbook,
ID_STA_Line4_BookUnbook,
ID_STA_Line5_BookUnbook,
ID_STA_Note_BookUnbook,
ID_LBX_Price_BookUnbook,
ID_STA_ExitIco_BookUnbook,
ID_STA_OkIco_BookUnbook,
ID_STA_ExitMenu_BookUnbook,
ID_STA_Ok_BookUnbook,
ID_STA_03_BookUnbook,
ID_SBR_BookUnbook,
ID_STA_zhouqi_BookUnbook,
ID_TBX_BookUnbook,
ID_STA_Color_BookUnbook,

//订购/退订IPP节目信息框

ID_DLG_BookUnbookInfo,
ID_STA_BookUnbookInfo,
ID_STA_OKIco_BookUnbookInfo,
ID_TIM_BookUnbookInfo,

//实时订购

ID_DLG_RealtimeBook,
ID_STA_RealtimeBook,
ID_STA_Name_RealtimeBook,
ID_STA_ProType_RealtimeBook,
ID_STA_Start_RealtimeBook,
ID_STA_Duration_RealtimeBook,
ID_STA_Booked_RealtimeBook,
ID_STA_PriceType_RealtimeBook,
ID_LBX_RealtimeBook,
ID_STA_EnterPIN_RealtimeBook,
ID_TBX_RealtimeBook,
ID_STA_Note_RealtimeBook,
ID_STA_SelectIco_RealtimeBook,
ID_STA_Choose_RealtimeBook,
ID_STA_OKIco_RealtimeBook,
ID_STA_OK_RealtimeBook,
ID_STA_ExitIco_RealtimeBook,
ID_STA_Exit_RealtimeBook,
ID_STA_Zhouqi_RealtimeBook,
ID_TBX_Zhouqi_RealtimeBook,
ID_STA_ReturnIco_RealtimeBook,
ID_STA_ReturnMenu_RealtimeBook,
ID_BK_RealtimeBook,

//已观看IPP节目信息

ID_DLG_ViewedIPP,
ID_STA_ViewedIPP,
ID_STA_Text_ViewedIPP,
ID_STA_Title_ViewedIPP,
ID_STA_TextBk_ViewedIPP,
ID_STA_Line1_ViewedIPP,
ID_STA_Line2_ViewedIPP,
ID_STA_Name_ViewedIPP,
ID_STA_Servicer_ViewedIPP,
ID_LBP_ViewedIPP,
ID_STA_SelectIco_ViewedIPP,
ID_STA_Select_ViewedIPP,
ID_STA_ExitIco_ViewedIPP,
ID_STA_Exit_ViewedIPP,
ID_STA_Line4_ViewedIPP,
ID_STA_Line3_ViewedIPP,
ID_SBR_ViewedIPP,
ID_STA_Prompt_ViewedIPP,

//验证用户的PIN码

ID_DLG_VerifyPin,
ID_STA_InputPin_VerifyPin,
ID_TBX_Pin_VerifyPin,
ID_STA_Note_VerifyPin,
ID_STA_NoteBk_VerifyPin,
ID_STA_ExitIco_VerifyPin,
ID_STA_InNumber_VerifyPin,
ID_STA_ExitMenu_VerifyPin,
ID_STA_OkIco_VerifyPin,
ID_STA_Ok_VerifyPin,
ID_STA_Title_VerifyPin,

//互动帮助

ID_DLG_DoubleHelp,
ID_STA_Title_DoubleHelp,
ID_STA_Time_DoubleHelp,
ID_STA_CardState_DoubleHelp,
ID_VFM_DoubleHelp,
ID_STA_ExitIco_DoubleHelp,
ID_STA_ExitStr_DoubleHelp,
ID_STA_Event1_DoubleHelp,
ID_STA_Event2_DoubleHelp,
ID_EDT_DoubleHelp,
ID_PBR_Epg_DoubleHelp,

//epg详细信息

ID_DLG_EPGDetail,
ID_STA_Title_EPGDetail,
ID_EDT_Detail_EPGDetail,
ID_STA_EventName_EPGDetail,
ID_STA_BK_EPGDetail,

//播放器对话框

ID_DLG_Player,
ID_STA_DisplaySetText_Player,
ID_STA_NameAndArtist_Player,
ID_STA_CTL_Player,
ID_PBR_Player,
ID_PBR_Volume_Player,
ID_ODC_CurTime_Player,
ID_STA_DisplaySetIcon_Player,
ID_STA_Player,
ID_STA_PlayerBk_Player,
ID_LBP_Player,
ID_SBR_Player,
ID_STA_Title_Player,
ID_STA_PlayerListBk_Player,
ID_STA_PlayerFileListShowBK_Player,
ID_LBP_DisplaySet_Player,
ID_STA_DisplaySetTitle_Player,
ID_STA_DisplaySet_Player,
ID_STA_PlayerDisplayShowBk_Player,
ID_VFM_Player,
ID_TIM_Player,

//数码相框

ID_DLG_PhotoFrame,
ID_ODC_Frame_PhotoFrame,
ID_STA_Title_PhotoFrame,
ID_STA_StaticName_PhotoFrame,
ID_STA_PhotoIndex_PhotoFrame,
ID_STA_StaticIndex_PhotoFrame,
ID_CBX_Order_PhotoFrame,
ID_CBX_Effect_PhotoFrame,
ID_CBX_Seconds_PhotoFrame,
ID_STA_StaticTotal_PhotoFrame,
ID_STA_PhotoTotal_PhotoFrame,
ID_STA_PhotoName_PhotoFrame,
ID_CBX_FullScreen_PhotoFrame,
ID_STA_ExitIcon_PhotoFrame,
ID_STA_Exit_PhotoFrame,
ID_STA_OKIcon_PhotoFrame,
ID_STA_OK_PhotoFrame,
ID_STA_LR_PhotoFrame,
ID_STA_LRIcon_PhotoFrame,
ID_STA_7,
ID_STA_8


}GUI_WinID_Demo_e;

#endif
