
#ifndef _HARDWARE_H
#define _HARDWARE_H

#define 	E2PROM_HAVE					(0)
#define 	HW_E2PROM_TYPE				(4)

#define	FRONTEND_TYPE					(0)

#define 	HARDWARETUNER_3130			(0)
#define 	HARDWARETUNER_NXP1216S		(1)
#define 	HARDWARETUNER_QX				(2)
#define 	HARDWARETUNER_DMB_T			(3)

#define	HARDWARETUNER_PORT			(0)
#define	HARDWARETUNER_TYPE			(HARDWARETUNER_NXP1216S)

#define	HARDWARERF_TYPE				(0)

#define	HARDWAREFLASH_TYPE			(0)

#define	HARDWAREIR_RCU1				(0)
#define	HARDWAREIR_RCU2				(1)
#define	HARDWAREIR_RCU3				(2)
#define	HARDWAREIR_RCU4				(3)

#define	HARDWAREIR_TYPE				(HARDWAREIR_RCU1)

#endif
