/*******************************************************************************
 *             Copyright 2004 - 2050, Hisilicon Tech. Co., Ltd.
 *                           ALL RIGHTS RESERVED
 * FileName: message_id.h
 * Description: 
 *
 * History:
 * Version   Date         Author     DefectNum    Description
 * main1     2006-12-4   liyuequan                
 ******************************************************************************/
#ifndef __MSG_EVENT__
#define __MSG_EVENT__

#include "hi_type.h"

#ifdef __cplusplus
#if __cplusplus
extern "C"{
#endif
#endif

typedef struct hiMsG_MESSAGE_S
{
    HI_U32  u32MessageID;
    HI_S32  s32Para1; 
    HI_S32  s32Para2; 
    HI_S32  s32Para3; 
}MSG_MESSAGE_S;

#define MESSAGE_UI_GROUP                      	0x10000000
#define MESSAGE_MNG_GROUP                   	0x20000000
#define MESSAGE_SUPPORT_GROUP        	0x40000000
#define MESSAGE_MEDIUM_GROUP        		0x80000000

#define MESSAGE_FP_GROUP                    	0x01000000
#define MESSAGE_IR_GROUP                     	0x02000000

#define MESSAGE_APPMNGSVR_GROUP         0x00100000
#define MESSAGE_AVSVR_GROUP            	0x00200000
#define MESSAGE_PGSVR_GROUP            	0x00300000
#define MESSAGE_BOOKSVR_GROUP        	0x00400000
#define MESSAGE_EPGSVR_GROUP            	0x00500000
#define MESSAGE_NVODSVR_GROUP        	0x00600000
#define MESSAGE_TUNERSVR_GROUP        	0x00700000
#define MESSAGE_SECTIONSVR_GROUP        0x00800000
#define MESSAGE_CMDLINE_GROUP        	0x00900000


#define MESSAGE_NETWORKSVR_GROUP	0x00B00000
#define MESSAGE_MEDIUMSVR_GROUP		0x00C00000
#define MESSAGE_CASVR_GROUP			0x00D00000

#define UI_MENU                             			0x00000000
#define UI_EXIT                                    		0x00000001
#define UI_OK                                       		0x00000002
#define UI_UP                                  		0x00000003
#define UI_DOWN                                  		0x00000004
#define UI_LEFT                              			0x00000005
#define UI_RIGHT                                 		0x00000006
#define UI_PAGEDOWN                    		0x00000007
#define UI_PAGEUP                          		0x00000008
#define UI_CH_UP                				0x00000009
#define UI_CH_DOWN                  			0x0000000A
#define UI_VOL_UP                      			0x0000000B
#define UI_VOL_DOWN                  			0x0000000C
#define UI_MUTE                     				0x0000000D
#define UI_TRACK                    				0x0000000E
#define UI_INFO                         			0x0000000F
#define UI_GUIDE                        			0x00000010
#define UI_RECALL                       			0x00000011
#define UI_TV_RADIO             				0x00000012
#define UI_RED                      				0x00000013
#define UI_YELLOW            				0x00000014
#define UI_BLUE                					0x00000015
#define UI_GREEN            					0x00000016
#define UI_POWER            					0x00000017


#define UI_NUM0                     0x00001000
#define UI_NUM1                     0x00001100
#define UI_NUM2                     0x00001200
#define UI_NUM3                     0x00001300
#define UI_NUM4                     0x00001400
#define UI_NUM5                     0x00001500
#define UI_NUM6                     0x00001600
#define UI_NUM7                     0x00001700
#define UI_NUM8                     0x00001800
#define UI_NUM9                     0x00001900



#define MESSAGE_UI_FP_MENU \
    (MESSAGE_UI_GROUP| MESSAGE_FP_GROUP| UI_MENU )
#define MESSAGE_UI_FP_EXIT \
    (MESSAGE_UI_GROUP| MESSAGE_FP_GROUP| UI_EXIT)
#define MESSAGE_UI_FP_OK \
    (MESSAGE_UI_GROUP| MESSAGE_FP_GROUP| UI_OK)
#define MESSAGE_UI_FP_UP \
    (MESSAGE_UI_GROUP| MESSAGE_FP_GROUP| UI_UP)
#define MESSAGE_UI_FP_DOWN \
    (MESSAGE_UI_GROUP| MESSAGE_FP_GROUP| UI_DOWN)
#define MESSAGE_UI_FP_LEFT \
    (MESSAGE_UI_GROUP| MESSAGE_FP_GROUP| UI_LEFT)
#define MESSAGE_UI_FP_RIGHT \
    (MESSAGE_UI_GROUP| MESSAGE_FP_GROUP| UI_RIGHT)
#define MESSAGE_UI_FP_POWER \
    (MESSAGE_UI_GROUP| MESSAGE_FP_GROUP| UI_POWER)
#define MESSAGE_UI_FP_NOKEY \
    (MESSAGE_UI_GROUP| MESSAGE_FP_GROUP| 0x0000ffff)


#define MESSAGE_UI_IR_MENU \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_MENU )
#define MESSAGE_UI_IR_EXIT \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_EXIT)
#define MESSAGE_UI_IR_OK \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_OK)
#define MESSAGE_UI_IR_UP \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_UP)
#define MESSAGE_UI_IR_DOWN \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_DOWN)
#define MESSAGE_UI_IR_LEFT \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_LEFT)
#define MESSAGE_UI_IR_RIGHT \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_RIGHT)

#define MESSAGE_UI_IR_PAGEDOWN \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_PAGEDOWN)
#define MESSAGE_UI_IR_PAGEUP \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_PAGEUP)
#define MESSAGE_UI_IR_CH_UP \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_CH_UP)
#define MESSAGE_UI_IR_CH_DOWN \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_CH_DOWN)
#define MESSAGE_UI_IR_VOL_UP \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_VOL_UP)
#define MESSAGE_UI_IR_VOL_DOWN \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_VOL_DOWN)
#define MESSAGE_UI_IR_MUTE \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_MUTE)
#define MESSAGE_UI_IR_TRACK \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_TRACK)
#define MESSAGE_UI_IR_INFO \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_INFO)
#define MESSAGE_UI_IR_GUIDE \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_GUIDE)
#define MESSAGE_UI_IR_RECALL \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_RECALL)
#define MESSAGE_UI_IR_TV_RADIO \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_TV_RADIO)
#define MESSAGE_UI_IR_RED \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_RED)
#define MESSAGE_UI_IR_YELLOW \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_YELLOW)
#define MESSAGE_UI_IR_BLUE \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_BLUE)
#define MESSAGE_UI_IR_GREEN \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_GREEN)

#define MESSAGE_UI_IR_NUM0 \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_NUM0)
#define MESSAGE_UI_IR_NUM1 \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_NUM1)
#define MESSAGE_UI_IR_NUM2 \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_NUM2)
#define MESSAGE_UI_IR_NUM3 \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_NUM3)
#define MESSAGE_UI_IR_NUM4 \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_NUM4)
#define MESSAGE_UI_IR_NUM5 \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_NUM5)
#define MESSAGE_UI_IR_NUM6 \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_NUM6)
#define MESSAGE_UI_IR_NUM7 \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_NUM7)
#define MESSAGE_UI_IR_NUM8 \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_NUM8)
#define MESSAGE_UI_IR_NUM9 \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_NUM9)
    
#define MESSAGE_UI_IR_POWER \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| UI_POWER)

#define MESSAGE_UI_IR_NOKEY \
    (MESSAGE_UI_GROUP| MESSAGE_IR_GROUP| 0x0000ffff)


/*********APPMNGSVR  MESSAGE EVENT**************/
#define MESSAGE_APPMNGSVR_CONNECT \
    (MESSAGE_MNG_GROUP| MESSAGE_APPMNGSVR_GROUP |0x00000001)
#define MESSAGE_APPMNGSVR_DISCONNECT \
    (MESSAGE_MNG_GROUP| MESSAGE_APPMNGSVR_GROUP |0x00000002)
#define MESSAGE_APPMNGSVR_SERVICESTART \
    (MESSAGE_MNG_GROUP| MESSAGE_APPMNGSVR_GROUP |0x00000003)
#define MESSAGE_APPMNGSVR_SERVICESTOP \
    (MESSAGE_MNG_GROUP| MESSAGE_APPMNGSVR_GROUP |0x00000004)


/*********AVSVR  MESSAGE EVENT**************/
#define MESSAGE_AVSVR_EPGPF_CHANGE \
    (MESSAGE_MNG_GROUP| MESSAGE_AVSVR_GROUP|0x000000B)
#define MESSAGE_AVSVR_SYSDATETIME_CHANGE \
    (MESSAGE_MNG_GROUP| MESSAGE_AVSVR_GROUP|0x000000C)
#define MESSAGE_AVSVR_PROG_CHANGE \
    (MESSAGE_MNG_GROUP| MESSAGE_AVSVR_GROUP|0x000000D)
#define MESSAGE_AVSVR_CHILDREQEST \
    (MESSAGE_MNG_GROUP| MESSAGE_AVSVR_GROUP|0x000000E)
#define MESSAGE_AVSVR_CHILDCHECK \
    (MESSAGE_MNG_GROUP| MESSAGE_AVSVR_GROUP|0x000000F)

#define MESSAGE_AVSVR_AVDECODESTART \
    (MESSAGE_MNG_GROUP| MESSAGE_AVSVR_GROUP|0x0000010)
#define MESSAGE_AVSVR_STOPOK \
    (MESSAGE_MNG_GROUP| MESSAGE_AVSVR_GROUP|0x0000011)

#define MESSAGE_AVSVR_STARTLAST \
    (MESSAGE_MNG_GROUP| MESSAGE_AVSVR_GROUP|0x0000012)	

		
/*********EPGSVR  MESSAGE EVENT**************/
#define MESSAGE_EPGSVR_EPGEVENT_CHANGE \
    (MESSAGE_MNG_GROUP| MESSAGE_EPGSVR_GROUP|0x0000015)

/*********PGSVR  MESSAGE EVENT**************/
#define MESSAGE_PGSVR_NITSEARCH_END \
    (MESSAGE_MNG_GROUP| MESSAGE_EPGSVR_GROUP|0x0000016)
#define MESSAGE_PGSVR_PROGSEARCH_END \
    (MESSAGE_MNG_GROUP| MESSAGE_EPGSVR_GROUP|0x0000017)

#define MESSAGE_PGSVR_SEARCH_END \
    (MESSAGE_MNG_GROUP| MESSAGE_EPGSVR_GROUP|0x0000018)



/*********NVODSVR  MESSAGE EVENT**************/
#define MESSAGE_NVODSVR_NVODNIT_END \
    (MESSAGE_MNG_GROUP| MESSAGE_NVODSVR_GROUP|0x0000019)
#define MESSAGE_NVODSVR_NVODPROG_END \
    (MESSAGE_MNG_GROUP| MESSAGE_NVODSVR_GROUP|0x0000020)
#define MESSAGE_NVODSVR_NVODEVENT_END \
    (MESSAGE_MNG_GROUP| MESSAGE_NVODSVR_GROUP|0x0000021)

/*********BOOKSVR  MESSAGE EVENT**************/
#define MESSAGE_BOOKSVR_TIMEOUT \
    (MESSAGE_MNG_GROUP| MESSAGE_BOOKSVR_GROUP|0x0000026)
#define MESSAGE_BOOKSVR_ALARM \
    (MESSAGE_MNG_GROUP| MESSAGE_BOOKSVR_GROUP|0x0000027)
#define MESSAGE_BOOKSVR_ALARM_ANSWER \
    (MESSAGE_MNG_GROUP| MESSAGE_BOOKSVR_GROUP|0x0000028)
#define MESSAGE_BOOKSVR_1S_TIMER \
    (MESSAGE_MNG_GROUP| MESSAGE_BOOKSVR_GROUP|0x0000029)

/*********TUNSVR MESSAGE EVENT**************/
#define MESSAGE_TUNERSVR_START \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_TUNERSVR_GROUP|0x0000026)
#define MESSAGE_TUNERSVR_STOP \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_TUNERSVR_GROUP|0x0000027)
#define MESSAGE_TUNERSVR_LOCK \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_TUNERSVR_GROUP|0x0000028)
#define MESSAGE_TUNERSVR_LOST \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_TUNERSVR_GROUP|0x0000029)
#define MESSAGE_TUNERSVR_DROP \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_TUNERSVR_GROUP|0x000002A)
#define MESSAGE_TUNERSVR_UNLOCK \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_TUNERSVR_GROUP|0x000002B)
#define MESSAGE_TUNERSVR_CHECK_TIMER \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_TUNERSVR_GROUP|0x000002C)
#define MESSAGE_TUNERSVR_ID \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_TUNERSVR_GROUP|0x000002D)


#define MESSAGE_CA_CHECK_TIME \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CASVR_GROUP|0x00000001)

#define MESSAGE_CA_CARD_IN \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CASVR_GROUP|0x00000002)

#define MESSAGE_CA_CARD_OUT \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CASVR_GROUP|0x00000003)

#define MESSAGE_CA_CARD_RESET \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CASVR_GROUP|0x00000004)

#define MESSAGE_CA_CARD_SENDECM \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CASVR_GROUP|0x00000005)

#define MESSAGE_CA_CARD_SENDEMM \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CASVR_GROUP|0x00000006)

#define MESSAGE_CA_CARD_FILTERSTART \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CASVR_GROUP|0x00000007)

#define MESSAGE_CA_CARD_FILTERSTOP \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CASVR_GROUP|0x00000008)

#define MESSAGE_CA_START \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CASVR_GROUP|0x00000009)

#define MESSAGE_CA_STOP \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CASVR_GROUP|0x0000000a)


#define MESSAGE_CA_CARD_FILTERRESET \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CASVR_GROUP|0x0000000c)


/*********NETWORKSVR MESSAGE EVENT**************/
#define MESSAGE_NETWORKSVR_START \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_NETWORKSVR_GROUP|0x0000001)
#define MESSAGE_NETWORKSVR_STOP \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_NETWORKSVR_GROUP|0x0000002)

#define MESSAGE_NETWORKSVR_CONNECT \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_NETWORKSVR_GROUP|0x0000003)
#define MESSAGE_NETWORKSVR_DISCONNECT \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_NETWORKSVR_GROUP|0x0000004)


#define MESSAGE_USB_FILECONNECT \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_NETWORKSVR_GROUP|0x0000005)
#define MESSAGE_USB_FILEDISCONNECT \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_NETWORKSVR_GROUP|0x0000006)

/*********MEDIUMSVR MESSAGE EVENT**************/
#define MESSAGE_MEDIUMSVR_CONNECT \
    (MESSAGE_MEDIUM_GROUP| MESSAGE_MEDIUMSVR_GROUP|0x0000001)
#define MESSAGE_MEDIUMSVR_DISCONNECT \
    (MESSAGE_MEDIUM_GROUP| MESSAGE_MEDIUMSVR_GROUP|0x0000002)
#define MESSAGE_MEDIUMSVR_GETFILELIST \
    (MESSAGE_MEDIUM_GROUP| MESSAGE_MEDIUMSVR_GROUP|0x0000003)   
#define MESSAGE_MEDIUMSVR_FILELIST \
    (MESSAGE_MEDIUM_GROUP| MESSAGE_MEDIUMSVR_GROUP|0x0000004)
#define MESSAGE_MEDIUMSVR_GETFILEINFO \
    (MESSAGE_MEDIUM_GROUP| MESSAGE_MEDIUMSVR_GROUP|0x0000005)
#define MESSAGE_MEDIUMSVR_FILEINFO \
    (MESSAGE_MEDIUM_GROUP| MESSAGE_MEDIUMSVR_GROUP|0x0000006)
#define MESSAGE_MEDIUMSVR_FILECTL \
    (MESSAGE_MEDIUM_GROUP| MESSAGE_MEDIUMSVR_GROUP|0x0000007)
#define MESSAGE_MEDIUMSVR_FILESTATE \
    (MESSAGE_MEDIUM_GROUP| MESSAGE_MEDIUMSVR_GROUP|0x0000008)
#define MESSAGE_MEDIUMSVR_FILEEND \
    (MESSAGE_MEDIUM_GROUP| MESSAGE_MEDIUMSVR_GROUP|0x0000009)


/*********SECTIONSVR  MESSAGE EVENT**************/
#define MESSAGE_SECTIONSVR_START \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_SECTIONSVR_GROUP|0x0000030)
#define MESSAGE_SECTIONSVR_STOP \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_SECTIONSVR_GROUP|0x0000031)
#define MESSAGE_SECTIONSVR_SECTION \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_SECTIONSVR_GROUP|0x0000032)
#define MESSAGE_SECTIONSVR_TIMEOUT \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_SECTIONSVR_GROUP|0x0000033)
#define MESSAGE_SECTIONSVR_TABLEFINISHED \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_SECTIONSVR_GROUP|0x0000034)
#define MESSAGE_SECTIONSVR_TIMER \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_SECTIONSVR_GROUP|0x0000035)
#define MESSAGE_SECTIONSVR_STOPFINISHED \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_SECTIONSVR_GROUP|0x0000036)



/*********CMD  MESSAGE EVENT**************/
#define MESSAGE_CMDLINE_ADDCHANNEL \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x0000001)

#define MESSAGE_CMDLINE_ADDRATE  \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x0000002)

#define MESSAGE_CMDLINE_ADDQAM  \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x0000003)


#define MESSAGE_CMDLINE_LISTCHANNEL  \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x0000007)

#define MESSAGE_CMDLINE_SEARCHPG  \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x0000008)

#define MESSAGE_CMDLINE_PLAYPG  \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x0000009)

#define MESSAGE_CMDLINE_LISTPG  \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x000000a)

#define MESSAGE_CMDLINE_GETSIGNAL  \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x000000b)

#define MESSAGE_CMDLINE_GETPGINFO  \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x000000c)


#define MESSAGE_CMDLINE_RESTRORE  \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x000000d)

#define MESSAGE_CMDLINE_ADDPG  \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x000000e)

#define MESSAGE_CMDLINE_STOPSER  \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x000000f)

#define MESSAGE_CMDLINE_STARTSER  \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x0000010)
    
#define MESSAGE_CMDLINE_STARTTEST \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x0000011)

#define MESSAGE_CMDLINE_STOPTEST \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x0000012)

#define MESSAGE_CMDLINE_TESTTIMEOUT \
    (MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x0000013)



/* debug qwdiao
#define MESSAGE_CMDLINE_STARTNVODNIT  \
(MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x0000011)

#define MESSAGE_CMDLINE_STARTNVOD  \
(MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x0000012)


#define MESSAGE_CMDLINE_NVODLISTCHANNEL  \
(MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x0000013)

#define MESSAGE_CMDLINE_LISTREFER  \
(MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x0000014)

#define MESSAGE_CMDLINE_LISTEVENT  \
(MESSAGE_SUPPORT_GROUP| MESSAGE_CMDLINE_GROUP|0x0000015)*/
#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif

#endif/*__MSG_EVENT__*/

