/**************************************
Author        : Hisilicon multime
Created       : 2006/3/6         
Last Modified :                  
Description   : ESS系统共用的错误码
Function List :                  
History       :                  
 *********************************/
#ifndef __ESS_ERRCODE_H__      
#define __ESS_ERRCODE_H__      



#ifdef __cplusplus               
#if __cplusplus                  
extern "C"{                      
#endif                           
#endif /* __cplusplus */         




#define MID_IR        0x30
#define MID_SC        0x31
#define MID_PMoC      0x32
#define MID_RTC       0x33
#define MID_WDG       0x34
#define MID_I2C       0x35
#define MID_GPIO      0x36
#define MID_E2PROM    0x37
#define MID_TUNER     0x38
#define MID_SCI       0x39
#define MID_KEYLED    0x3B  
#define MID_INDICATOR 0x3C  
#define MID_DMAC      0x3D
#define MID_CIPHER	  0x3E
#define MID_ETH	        0x3F

#ifndef __HI_LOG_LEVEL_E__
#define __HI_LOG_LEVEL_E__

typedef enum hiLOG_ERRLEVEL_E
{
    HI_LOG_LEVEL_DEBUG = 0,  
    HI_LOG_LEVEL_INFO ,      
    HI_LOG_LEVEL_NOTICE,     
    HI_LOG_LEVEL_WARNING,    
    HI_LOG_LEVEL_ERROR,      
    HI_LOG_LEVEL_CRIT,       
    HI_LOG_LEVEL_ALERT,      
    HI_LOG_LEVEL_FATAL,      
    HI_LOG_LEVEL_BUTT
} LOG_ERRLEVEL_E;



/******************************************************************************
  |----------------------------------------------------------------| 
  | 1 |   APP_ID   |   MOD_ID    | ERR_LEVEL |   ERR_ID            | 
  |----------------------------------------------------------------| 
  |<--><--7bits----><----8bits---><--3bits---><------13bits------->|
 ******************************************************************************/

#endif
#define HI_ERR_APPID  (0x80UL + 0x20UL)

#ifndef HI_DEF_ERR
#define HI_DEF_ERR( mid, level, errid) \
    ( ((HI_ERR_APPID)<<24) | ((mid) << 16 ) | ((level)<<13) | (errid) )
#endif

/***************************
  SCI 错误码定义
 ***************************/

enum hiSCI_ErrorCode_E
{
    ERR_SCI_NOT_INIT=0,
    ERR_SCI_REPEAT_INIT,
    ERR_SCI_INVALID_POINT,
    ERR_SCI_INVALID_PARA,
    ERR_SCI_FAILED_INIT,
    ERR_SCI_FAILED_RESET,
    ERR_SCI_FAILED_DEACTIVE,    
    ERR_SCI_FAILED_GETATR,
    ERR_SCI_FAILED_CARDSTATUS,
    ERR_SCI_FAILED_SEND,
    ERR_SCI_FAILED_RECEIVE,
    ERR_SCI_FAILED_TIMEOUT_VAL,
    ERR_SCI_FAILED_GET_DATA_LEN,
    ERR_SCI_FAILED_CONFIGVCCEN,
    ERR_SCI_FAILED_CONFIGDETECT,
    ERR_SCI_FAILED_BLK_CARDSTATUS,
    ERR_SCI_INVALID_PORT,
    ERR_SCI_INVALID_PROTOCOL,
    ERR_SCI_INVALID_FREQUENCY,
    ERR_SCI_INVALID_LENTH,
    ERR_SCI_NO_ATR,
    ERR_SCI_CARD_STATUS,
    ERR_SCI_RECEIVE_TIMEOUT,
    ERR_SCI_INVALID_TIMEOUT_VAL,
    ERR_SCI_INVALID_LEVEL_VAL,
    ERR_SCI_FAILED_BLK_TIMEOUT,
/* AI7D02725 start */
	ERR_SCI_FAILED_CONFIGSCIMODE
/* AI7D02725 end */
};

#define HI_ERR_SCI_NOT_INIT              HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_NOT_INIT)    /* 0xa0398000 */
#define HI_ERR_SCI_REPEAT_INIT           HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_REPEAT_INIT)
#define HI_ERR_SCI_INVALID_POINT         HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_INVALID_POINT)
#define HI_ERR_SCI_INVALID_PARA          HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_INVALID_PARA)
#define HI_ERR_SCI_FAILED_INIT           HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_FAILED_INIT)
#define HI_ERR_SCI_FAILED_RESET          HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_FAILED_RESET)
#define HI_ERR_SCI_FAILED_DEACTIVE       HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_FAILED_DEACTIVE)
#define HI_ERR_SCI_FAILED_GETATR         HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_FAILED_GETATR)
#define HI_ERR_SCI_FAILED_CARDSTATUS     HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_FAILED_CARDSTATUS)
#define HI_ERR_SCI_FAILED_SEND           HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_FAILED_SEND)
#define HI_ERR_SCI_FAILED_RECEIVE        HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_FAILED_RECEIVE)
#define HI_ERR_SCI_FAILED_TIMEOUT_VAL    HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_FAILED_TIMEOUT_VAL)
#define HI_ERR_SCI_FAILED_GET_DATA_LEN   HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_FAILED_GET_DATA_LEN)
#define HI_ERR_SCI_FAILED_CONFIGVCCEN    HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_FAILED_CONFIGVCCEN)
#define HI_ERR_SCI_FAILED_CONFIGDETECT   HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_FAILED_CONFIGDETECT)
#define HI_ERR_SCI_FAILED_BLK_CARDSTATUS HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_FAILED_BLK_CARDSTATUS)
#define HI_ERR_SCI_INVALID_PORT          HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_INVALID_PORT)
#define HI_ERR_SCI_INVALID_PROTOCOL      HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_INVALID_PROTOCOL)
#define HI_ERR_SCI_INVALID_FREQUENCY     HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_INVALID_FREQUENCY)
#define HI_ERR_SCI_INVALID_LENTH         HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_INVALID_LENTH)
#define HI_ERR_SCI_NO_ATR                HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_NO_ATR)
#define HI_ERR_SCI_CARD_STATUS           HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_CARD_STATUS)
#define HI_ERR_SCI_RECEIVE_TIMEOUT       HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_RECEIVE_TIMEOUT)
#define HI_ERR_SCI_INVALID_TIMEOUT_VAL   HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_INVALID_TIMEOUT_VAL)
#define HI_ERR_SCI_INVALID_LEVEL_VAL     HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_INVALID_LEVEL_VAL)
#define HI_ERR_SCI_FAILED_BLK_TIMEOUT    HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_FAILED_BLK_TIMEOUT)
/* AI7D02725 start */
#define HI_ERR_SCI_FAILED_CONFIGSCIMODE  HI_DEF_ERR(MID_SCI, HI_LOG_LEVEL_ERROR, ERR_SCI_FAILED_CONFIGSCIMODE)
/* AI7D02725 end */


/***************************
 	KEYLED error code define
 ***************************/
enum hiKEYLED_ErrorCode_E
{
    ERR_KEYLED_NOT_INIT = 0,
    ERR_KEYLED_REPEAT_INIT,
    ERR_KEYLED_INVALID_POINT,
    ERR_KEYLED_INVALID_PARA,
    ERR_KEYLED_FAILED_INIT,
    ERR_KEYLED_FAILED_READ,
    ERR_KEYLED_FAILED_ENABLE,
    ERR_KEYLED_FAILED_DISABLE,        
    ERR_KEYLED_FAILED_SET_ISKEYUP,
    ERR_KEYLED_FAILED_SET_ISREPKEY,
    ERR_KEYLED_FAILED_SET_REPKEYTIMEOUTVAL,
    ERR_KEYLED_FAILED_CLEARBUF,
    ERR_KEYLED_FAILED_SETBLOCKTIME,
    ERR_KEYLED_FAILED_SETFLASHPIN,
    ERR_KEYLED_FAILED_SETFLASHFREQ,
    ERR_KEYLED_FAILED_DISPLAY,
    ERR_KEYLED_FAILED_DISPLAYTIME,
    ERR_KEYLED_INVALID_ISKEYUP_ARG,
    ERR_KEYLED_INVALID_ISREPKEY_ARG,
    ERR_KEYLED_INVALID_TIME_ARG,
    ERR_KEYLED_BADFLASHPIN,
    ERR_KEYLED_BADFLASHFREQ,
    ERR_KEYLED_FAILED_SET_LEDTYPE,
    ERR_KEYLED_FAILED_SET_CSTYPE
};

#define HI_ERR_KEYLED_NOT_INIT       HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_NOT_INIT) //0xa03b8000
#define HI_ERR_KEYLED_REPEAT_INIT    HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_REPEAT_INIT)
#define HI_ERR_KEYLED_INVALID_POINT  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_INVALID_POINT)
#define HI_ERR_KEYLED_INVALID_PARA   HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_INVALID_PARA)
#define HI_ERR_KEYLED_FAILED_INIT  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_FAILED_INIT)
#define HI_ERR_KEYLED_FAILED_READ  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_FAILED_READ)
#define HI_ERR_KEYLED_FAILED_ENABLE  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_FAILED_ENABLE)
#define HI_ERR_KEYLED_FAILED_DISABLE  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_FAILED_DISABLE)
#define HI_ERR_KEYLED_FAILED_SET_ISKEYUP  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_FAILED_SET_ISKEYUP)
#define HI_ERR_KEYLED_FAILED_SET_ISREPKEY  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_FAILED_SET_ISREPKEY)
#define HI_ERR_KEYLED_FAILED_SET_REPKEYTIMEOUTVAL  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_FAILED_SET_REPKEYTIMEOUTVAL)
#define HI_ERR_KEYLED_FAILED_CLEARBUF  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_FAILED_CLEARBUF)
#define HI_ERR_KEYLED_FAILED_SETBLOCKTIME  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_FAILED_SETBLOCKTIME)
#define HI_ERR_KEYLED_FAILED_SETFLASHPIN  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_FAILED_SETFLASHPIN)
#define HI_ERR_KEYLED_FAILED_SETFLASHFREQ  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_FAILED_SETFLASHFREQ)
#define HI_ERR_KEYLED_FAILED_DISPLAY  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_FAILED_DISPLAY)
#define HI_ERR_KEYLED_FAILED_DISPLAYTIME  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_FAILED_DISPLAYTIME)
#define HI_ERR_KEYLED_INVALID_ISKEYUP_ARG   HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_INVALID_ISKEYUP_ARG)
#define HI_ERR_KEYLED_INVALID_ISREPKEY_ARG  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_INVALID_ISREPKEY_ARG)
#define HI_ERR_KEYLED_INVALID_TIME_ARG  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_INVALID_TIME_ARG)
#define HI_ERR_KEYLED_BADFLASHPIN  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_BADFLASHPIN)
#define HI_ERR_KEYLED_BADFLASHFREQ  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_BADFLASHFREQ)
#define HI_ERR_KEYLED_FAILED_SET_LEDTYPE  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_FAILED_SET_LEDTYPE)
#define HI_ERR_KEYLED_FAILED_SET_CSTYPE  HI_DEF_ERR(MID_KEYLED, HI_LOG_LEVEL_ERROR, ERR_KEYLED_FAILED_SET_CSTYPE)


/*****************
  RTC模块ID
 *****************/


/*RTC错误码子码定义*/
enum hiRTC_ErrorCode_E
{
    ERR_RTC_NOT_INIT = 0,
    ERR_RTC_REPEAT_INIT,
    ERR_RTC_INVALID_POINT,
    ERR_RTC_INVALID_PARA,
    ERR_RTC_FAILED_INIT,
    ERR_RTC_FAILED_SETTIME,
    ERR_RTC_FAILED_GETTIME,
    ERR_RTC_FAILED_ALARMENABLE,
    ERR_RTC_FAILED_ALARMDISABLE,
    ERR_RTC_FAILED_SETALARM,
    ERR_RTC_FAILED_GETALARM
};

/*RTC错误码定义*/
#define HI_ERR_RTC_NOT_INIT      HI_DEF_ERR(MID_RTC , HI_LOG_LEVEL_ERROR, ERR_RTC_NOT_INIT)
#define HI_ERR_RTC_REPEAT_INIT   HI_DEF_ERR(MID_RTC , HI_LOG_LEVEL_ERROR, ERR_RTC_REPEAT_INIT)
#define HI_ERR_RTC_INVALID_POINT HI_DEF_ERR(MID_RTC , HI_LOG_LEVEL_ERROR, ERR_RTC_INVALID_POINT)
#define HI_ERR_RTC_INVALID_PARA  HI_DEF_ERR(MID_RTC , HI_LOG_LEVEL_ERROR, ERR_RTC_INVALID_PARA)
#define HI_ERR_RTC_FAILED_INIT   HI_DEF_ERR(MID_RTC , HI_LOG_LEVEL_ERROR, ERR_RTC_FAILED_INIT)
#define HI_ERR_RTC_FAILED_SETTIME  HI_DEF_ERR(MID_RTC , HI_LOG_LEVEL_ERROR, ERR_RTC_FAILED_SETTIME)        
#define HI_ERR_RTC_FAILED_GETTIME  HI_DEF_ERR(MID_RTC , HI_LOG_LEVEL_ERROR, ERR_RTC_FAILED_GETTIME)        
#define HI_ERR_RTC_FAILED_ALARMENABLE  HI_DEF_ERR(MID_RTC , HI_LOG_LEVEL_ERROR, ERR_RTC_FAILED_ALARMENABLE)        
#define HI_ERR_RTC_FAILED_ALARMDISABLE  HI_DEF_ERR(MID_RTC , HI_LOG_LEVEL_ERROR, ERR_RTC_FAILED_ALARMDISABLE)        
#define HI_ERR_RTC_FAILED_SETALARM  HI_DEF_ERR(MID_RTC , HI_LOG_LEVEL_ERROR, ERR_RTC_FAILED_SETALARM)        
#define HI_ERR_RTC_FAILED_GETALARM  HI_DEF_ERR(MID_RTC , HI_LOG_LEVEL_ERROR, ERR_RTC_FAILED_GETALARM)        

/******************
  WDG模块ID
 *****************/

/*WDG错误码子码定义*/
enum hiWDG_ErrorCode_E
{
    ERR_WDG_NOT_INIT = 0,
    ERR_WDG_REPEAT_INIT,
    ERR_WDG_INVALID_POINT,
    ERR_WDG_INVALID_PARA,
    ERR_WDG_FAILED_INIT,
    ERR_WDG_FAILED_SETTIMEOUT,
    ERR_WDG_FAILED_ENABLE,
    ERR_WDG_FAILED_DISABLE,
    ERR_WDG_FAILED_CLEARWDG,
    ERR_WDG_FAILED_RESET,
    ERR_WDG_FAILED_RESMODE
};

/*WDG错误码定义*/
#define HI_ERR_WDG_NOT_INIT      HI_DEF_ERR(MID_WDG , HI_LOG_LEVEL_ERROR, ERR_WDG_NOT_INIT)
#define HI_ERR_WDG_REPEAT_INIT   HI_DEF_ERR(MID_WDG , HI_LOG_LEVEL_ERROR, ERR_WDG_REPEAT_INIT)
#define HI_ERR_WDG_INVALID_POINT HI_DEF_ERR(MID_WDG , HI_LOG_LEVEL_ERROR, ERR_WDG_INVALID_POINT)
#define HI_ERR_WDG_INVALID_PARA  HI_DEF_ERR(MID_WDG , HI_LOG_LEVEL_ERROR, ERR_WDG_INVALID_PARA)
#define HI_ERR_WDG_FAILED_INIT   HI_DEF_ERR(MID_WDG , HI_LOG_LEVEL_ERROR, ERR_WDG_FAILED_INIT)
#define HI_ERR_WDG_FAILED_SETTIMEOUT  HI_DEF_ERR(MID_WDG , HI_LOG_LEVEL_ERROR, ERR_WDG_FAILED_SETTIMEOUT)        
#define HI_ERR_WDG_FAILED_ENABLE   HI_DEF_ERR(MID_WDG , HI_LOG_LEVEL_ERROR, ERR_WDG_FAILED_ENABLE)        
#define HI_ERR_WDG_FAILED_DISABLE  HI_DEF_ERR(MID_WDG , HI_LOG_LEVEL_ERROR, ERR_WDG_FAILED_DISABLE)        
#define HI_ERR_WDG_FAILED_CLEARWDG HI_DEF_ERR(MID_WDG , HI_LOG_LEVEL_ERROR, ERR_WDG_FAILED_CLEARWDG)        
#define HI_ERR_WDG_FAILED_RESET    HI_DEF_ERR(MID_WDG , HI_LOG_LEVEL_ERROR, ERR_WDG_FAILED_RESET)        
#define HI_ERR_WDG_FAILED_RESMODE  HI_DEF_ERR(MID_WDG , HI_LOG_LEVEL_ERROR, ERR_WDG_FAILED_RESMODE)        

/**********************
	  	GPIO module
 **********************/
enum hiGPIO_ErrorCode_E
{
    ERR_GPIO_NOT_INIT,
    ERR_GPIO_REPEAT_INIT,
    ERR_GPIO_INVALID_POINT,
    ERR_GPIO_INVALID_PARA,
    ERR_GPIO_FAILED_INIT,
    ERR_GPIO_FAILED_DIRSET_BIT,
    ERR_GPIO_FAILED_DIRSET_BYTE,
    ERR_GPIO_FAILED_DIRGET_BIT,
    ERR_GPIO_FAILED_DIRGET_BYTE,
    ERR_GPIO_FAILED_WRITE_BIT,
    ERR_GPIO_FAILED_WRITE_BYTE,
    ERR_GPIO_FAILED_READ_BIT,
    ERR_GPIO_FAILED_READ_BYTE,
    ERR_GPIO_FAILED_SWITCH2LED,
    ERR_GPIO_FAILED_LED_DIRSET_BIT,
    ERR_GPIO_FAILED_LED_WRITE_BIT
};

#define HI_ERR_GPIO_NOT_INIT                       HI_DEF_ERR(MID_GPIO , HI_LOG_LEVEL_ERROR, ERR_GPIO_NOT_INIT)
#define HI_ERR_GPIO_REPEAT_INIT                    HI_DEF_ERR(MID_GPIO , HI_LOG_LEVEL_ERROR, ERR_GPIO_REPEAT_INIT)
#define HI_ERR_GPIO_INVALID_POINT                   HI_DEF_ERR(MID_GPIO , HI_LOG_LEVEL_ERROR, ERR_GPIO_INVALID_POINT)
#define HI_ERR_GPIO_INVALID_PARA                HI_DEF_ERR(MID_GPIO , HI_LOG_LEVEL_ERROR, ERR_GPIO_INVALID_PARA)
#define HI_ERR_GPIO_FAILED_INIT                    HI_DEF_ERR(MID_GPIO , HI_LOG_LEVEL_ERROR, ERR_GPIO_FAILED_INIT)
#define HI_ERR_GPIO_FAILED_DIRSET_BIT          HI_DEF_ERR(MID_GPIO , HI_LOG_LEVEL_ERROR, ERR_GPIO_FAILED_DIRSET_BIT)
#define HI_ERR_GPIO_FAILED_DIRSET_BYTE          HI_DEF_ERR(MID_GPIO , HI_LOG_LEVEL_ERROR, ERR_GPIO_FAILED_DIRSET_BYTE)
#define HI_ERR_GPIO_FAILED_DIRGET_BIT          HI_DEF_ERR(MID_GPIO , HI_LOG_LEVEL_ERROR, ERR_GPIO_FAILED_DIRGET_BIT)
#define HI_ERR_GPIO_FAILED_DIRGET_BYTE          HI_DEF_ERR(MID_GPIO , HI_LOG_LEVEL_ERROR, ERR_GPIO_FAILED_DIRGET_BYTE)
#define HI_ERR_GPIO_FAILED_WRITE_BIT          HI_DEF_ERR(MID_GPIO , HI_LOG_LEVEL_ERROR, ERR_GPIO_FAILED_WRITE_BIT)
#define HI_ERR_GPIO_FAILED_WRITE_BYTE          HI_DEF_ERR(MID_GPIO , HI_LOG_LEVEL_ERROR, ERR_GPIO_FAILED_WRITE_BYTE)
#define HI_ERR_GPIO_FAILED_READ_BIT          HI_DEF_ERR(MID_GPIO , HI_LOG_LEVEL_ERROR, ERR_GPIO_FAILED_READ_BIT)
#define HI_ERR_GPIO_FAILED_READ_BYTE          HI_DEF_ERR(MID_GPIO , HI_LOG_LEVEL_ERROR, ERR_GPIO_FAILED_READ_BYTE)
#define HI_ERR_GPIO_FAILED_SWITCH2LED          HI_DEF_ERR(MID_GPIO , HI_LOG_LEVEL_ERROR, ERR_GPIO_FAILED_SWITCH2LED)
#define HI_ERR_GPIO_FAILED_LED_DIRSET_BIT          HI_DEF_ERR(MID_GPIO , HI_LOG_LEVEL_ERROR, ERR_GPIO_FAILED_LED_DIRSET_BIT)
#define HI_ERR_GPIO_FAILED_LED_WRITE_BIT          HI_DEF_ERR(MID_GPIO , HI_LOG_LEVEL_ERROR, ERR_GPIO_FAILED_LED_WRITE_BIT)

/***************
  TUNER模块
 ***************/

/*TUNER错误码子码定义*/
enum hiTUNER_ErrorCode_E
{
    ERR_TUNER_NOT_INIT = 0,
    ERR_TUNER_REPEAT_INIT,
    ERR_TUNER_INVALID_POINT,
    ERR_TUNER_INVALID_PARA,
    ERR_TUNER_FAILED_INIT,
	ERR_TUNER_FAILED_CONNECT,
	ERR_TUNER_FAILED_GETSTATUS,
	ERR_TUNER_FAILED_GETSIGNALSTRENGTH,
	ERR_TUNER_FAILED_GETBER,
	ERR_TUNER_FAILED_GETSNR,
	ERR_TUNER_FAILED_SETTSTYPE,
	ERR_TUNER_FAILED_SELECTTUNER,
	ERR_TUNER_FAILED_SELECTI2CCHANNEL,
	ERR_TUNER_FAILED_LOWCONS,
	ERR_TUNER_FAILED_NORMALMODE,
	ERR_TUNER_FAILED_REGRW,
	ERR_TUNER_FAILED_SETTUNER,
	
	ERR_TUNER_NOT_CONNECT,
 	ERR_TUNER_INVALID_PORT,
	ERR_TUNER_FAILED_SETQAMINSIDE,
	ERR_TUNER_FAILED_SELECTSYMBOLRATE
};

/*TUNER错误码定义*/
#define  HI_ERR_TUNER_NOT_INIT           HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_NOT_INIT)
#define  HI_ERR_TUNER_REPEAT_INIT        HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_REPEAT_INIT)
#define  HI_ERR_TUNER_INVALID_POINT      HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_INVALID_POINT)
#define  HI_ERR_TUNER_INVALID_PARA       HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_INVALID_PARA)
#define  HI_ERR_TUNER_FAILED_INIT        HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_FAILED_INIT)
#define  HI_ERR_TUNER_FAILED_CONNECT        HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_FAILED_CONNECT)
#define  HI_ERR_TUNER_FAILED_GETSTATUS        HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_FAILED_GETSTATUS)
#define  HI_ERR_TUNER_FAILED_GETSIGNALSTRENGTH        HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_FAILED_GETSIGNALSTRENGTH)
#define  HI_ERR_TUNER_FAILED_GETBER        HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_FAILED_GETBER)
#define  HI_ERR_TUNER_FAILED_GETSNR        HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_FAILED_GETSNR)
#define  HI_ERR_TUNER_FAILED_SETTSTYPE        HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_FAILED_SETTSTYPE)
#define  HI_ERR_TUNER_FAILED_SELECTTUNER        HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_FAILED_SELECTTUNER)
#define  HI_ERR_TUNER_FAILED_SELECTI2CCHANNEL        HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_FAILED_SELECTI2CCHANNEL)
#define  HI_ERR_TUNER_FAILED_LOWCONS        HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_FAILED_LOWCONS)
#define  HI_ERR_TUNER_FAILED_NORMALMODE     HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_FAILED_NORMALMODE)
#define  HI_ERR_TUNER_FAILED_REGRW     HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_FAILED_REGRW)
#define  HI_ERR_TUNER_FAILED_SETTUNER     HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_FAILED_SETTUNER)
#define  HI_ERR_TUNER_NOT_CONNECT        HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_NOT_CONNECT)
#define  HI_ERR_TUNER_INVALID_PORT       HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_INVALID_PORT) 
#define HI_ERR_TUNER_FAILED_SETQAMINSIDE HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_FAILED_SETQAMINSIDE)
#define  HI_ERR_TUNER_FAILED_SELECTSYMBOLRATE        HI_DEF_ERR(MID_TUNER, HI_LOG_LEVEL_ERROR, ERR_TUNER_FAILED_SELECTSYMBOLRATE)

/***************
  I2C模块
 ***************/

/*I2C错误码子码定义*/
enum hiI2C_ErrorCode_E
{
    ERR_I2C_NOT_INIT = 0,
    ERR_I2C_REPEAT_INIT,
    ERR_I2C_INVALID_POINT,
    ERR_I2C_INVALID_PARA,
	ERR_I2C_FAILED_INIT,
	ERR_I2C_FAILED_READ,
	ERR_I2C_FAILED_WRITE,
	ERR_I2C_FAILED_SETRATE
};

/*I2C错误码定义*/
#define  HI_ERR_I2C_NOT_INIT          HI_DEF_ERR(MID_I2C, HI_LOG_LEVEL_ERROR, ERR_I2C_NOT_INIT)
#define  HI_ERR_I2C_REPEAT_INIT       HI_DEF_ERR(MID_I2C, HI_LOG_LEVEL_ERROR, ERR_I2C_REPEAT_INIT)
#define  HI_ERR_I2C_INVALID_POINT     HI_DEF_ERR(MID_I2C, HI_LOG_LEVEL_ERROR, ERR_I2C_INVALID_POINT)
#define  HI_ERR_I2C_INVALID_PARA      HI_DEF_ERR(MID_I2C, HI_LOG_LEVEL_ERROR, ERR_I2C_INVALID_PARA)
#define  HI_ERR_I2C_FAILED_INIT       HI_DEF_ERR(MID_I2C, HI_LOG_LEVEL_ERROR, ERR_I2C_FAILED_INIT)   
#define  HI_ERR_I2C_FAILED_READ		  HI_DEF_ERR(MID_I2C, HI_LOG_LEVEL_ERROR, ERR_I2C_FAILED_READ)
#define  HI_ERR_I2C_FAILED_WRITE	  HI_DEF_ERR(MID_I2C, HI_LOG_LEVEL_ERROR, ERR_I2C_FAILED_WRITE)
#define  HI_ERR_I2C_FAILED_SETRATE	  HI_DEF_ERR(MID_I2C, HI_LOG_LEVEL_ERROR, ERR_I2C_FAILED_SETRATE)


/***************
  E2PROM模块
 ***************/

/*E2PROM错误码子码定义*/
enum hiE2PROM_ErrorCode_E
{
    ERR_E2PROM_NOT_INIT = 0,
    ERR_E2PROM_REPEAT_INIT,
    ERR_E2PROM_INVALID_POINT,
    ERR_E2PROM_INVALID_PARA,
 	ERR_E2PROM_FAILED_INIT,
	ERR_E2PROM_FAILED_READ,
	ERR_E2PROM_FAILED_WRITE,
	ERR_E2PROM_FAILED_SETCHIPTYPE,
	ERR_E2PROM_FAILED_SETADDR,
	ERR_E2PROM_FAILED_SETI2CNUM
};

/*E2PROM错误码定义*/
#define  HI_ERR_E2PROM_NOT_INIT          HI_DEF_ERR(MID_E2PROM, HI_LOG_LEVEL_ERROR, ERR_E2PROM_NOT_INIT)
#define  HI_ERR_E2PROM_REPEAT_INIT       HI_DEF_ERR(MID_E2PROM, HI_LOG_LEVEL_ERROR, ERR_E2PROM_REPEAT_INIT)
#define  HI_ERR_E2PROM_INVALID_POINT     HI_DEF_ERR(MID_E2PROM, HI_LOG_LEVEL_ERROR, ERR_E2PROM_INVALID_POINT)
#define  HI_ERR_E2PROM_INVALID_PARA      HI_DEF_ERR(MID_E2PROM, HI_LOG_LEVEL_ERROR, ERR_E2PROM_INVALID_PARA)
#define  HI_ERR_E2PROM_FAILED_INIT       HI_DEF_ERR(MID_E2PROM, HI_LOG_LEVEL_ERROR, ERR_E2PROM_FAILED_INIT)
#define  HI_ERR_E2PROM_FAILED_READ       HI_DEF_ERR(MID_E2PROM, HI_LOG_LEVEL_ERROR, ERR_E2PROM_FAILED_READ)
#define  HI_ERR_E2PROM_FAILED_WRITE       HI_DEF_ERR(MID_E2PROM, HI_LOG_LEVEL_ERROR, ERR_E2PROM_FAILED_WRITE)
#define  HI_ERR_E2PROM_FAILED_SETCHIPTYPE 	HI_DEF_ERR(MID_E2PROM, HI_LOG_LEVEL_ERROR, ERR_E2PROM_FAILED_SETCHIPTYPE)
#define  HI_ERR_E2PROM_FAILED_SETADDR 		HI_DEF_ERR(MID_E2PROM, HI_LOG_LEVEL_ERROR, ERR_E2PROM_FAILED_SETADDR)
#define  HI_ERR_E2PROM_FAILED_SETI2CNUM 	HI_DEF_ERR(MID_E2PROM, HI_LOG_LEVEL_ERROR, ERR_E2PROM_FAILED_SETI2CNUM)

/***************
  IR module
 ***************/

/*IR sub error code define*/
enum hiIR_ErrorCode_E
{
    ERR_IR_NOT_INIT = 0,
    ERR_IR_REPEAT_INIT,    
    ERR_IR_INVALID_POINT,
    ERR_IR_INVALID_PARA,
    ERR_IR_FAILED_INIT,
    ERR_IR_FAILED_READ,
    ERR_IR_FAILED_ENABLE,
    ERR_IR_FAILED_DISABLE,
    ERR_IR_FAILED_SET_ISKEYUP,
    ERR_IR_FAILED_SET_ISREPKEY,
    ERR_IR_FAILED_SET_REPKEYTIMEOUTVAL,
    ERR_IR_FAILED_SET_CODETYPE,
    ERR_IR_FAILED_SET_USERCODE,
    ERR_IR_FAILED_CLEARBUF,
    ERR_IR_FAILED_SETBLOCKTIME,
    ERR_IR_INVALID_ISKEYUP_ARG,
    ERR_IR_INVALID_ISREPKEY_ARG,
    ERR_IR_INVALID_CODETYPE      
};

/*IR error code define*/
#define  HI_ERR_IR_NOT_INIT                  HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_NOT_INIT)
#define  HI_ERR_IR_REPEAT_INIT               HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_REPEAT_INIT)
#define HI_ERR_IR_INVALID_POINT          HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_INVALID_POINT)
#define  HI_ERR_IR_INVALID_PARA              HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_INVALID_PARA)
#define  HI_ERR_IR_FAILED_INIT               HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_FAILED_INIT)   
#define  HI_ERR_IR_FAILED_READ               HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_FAILED_READ)   
#define  HI_ERR_IR_FAILED_ENABLE             HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_FAILED_ENABLE)
#define  HI_ERR_IR_FAILED_DISABLE            HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_FAILED_DISABLE)
#define HI_ERR_IR_FAILED_SET_ISKEYUP          HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_FAILED_SET_ISKEYUP)
#define HI_ERR_IR_FAILED_SET_ISREPKEY        HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_FAILED_SET_ISREPKEY)
#define HI_ERR_IR_FAILED_SET_REPKEYTIMEOUTVAL        HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_FAILED_SET_REPKEYTIMEOUTVAL)
#define HI_ERR_IR_FAILED_SET_CODETYPE        HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_FAILED_SET_CODETYPE)
#define HI_ERR_IR_FAILED_SET_USERCODE        HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_FAILED_SET_USERCODE)
#define HI_ERR_IR_FAILED_CLEARBUF        HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_FAILED_CLEARBUF)
#define HI_ERR_IR_FAILED_SETBLOCKTIME        HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_FAILED_SETBLOCKTIME)
#define HI_ERR_IR_INVALID_ISKEYUP_ARG   HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_INVALID_ISKEYUP_ARG)
#define HI_ERR_IR_INVALID_ISREPKEY_ARG  HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_INVALID_ISREPKEY_ARG)
#define HI_ERR_IR_INVALID_CODETYPE          HI_DEF_ERR(MID_IR, HI_LOG_LEVEL_ERROR, ERR_IR_INVALID_CODETYPE)


/*CIPHER sub error code define*/
enum hiCIPHER_ErrorCode_E
{
    ERR_CIPHER_NOT_INIT = 0,
    ERR_CIPHER_REPEAT_INIT,    
    ERR_CIPHER_INVALID_POINT,
    ERR_CIPHER_INVALID_PARA,
    ERR_CIPHER_FAILED_INIT,
	ERR_CIPHER_FAILED_GETHANDLE,
	ERR_CIPHER_FAILED_RELEASEHANDLE,
	ERR_CIPHER_FAILED_CONFIGAES,
	ERR_CIPHER_FAILED_CONFIGDES,
	ERR_CIPHER_FAILED_ENCRYPT,
	ERR_CIPHER_FAILED_DECRYPT
};

/*CIPHER error code define*/
#define  HI_ERR_CIPHER_NOT_INIT                  HI_DEF_ERR(MID_CIPHER, HI_LOG_LEVEL_ERROR, ERR_CIPHER_NOT_INIT)
#define  HI_ERR_CIPHER_REPEAT_INIT               HI_DEF_ERR(MID_CIPHER, HI_LOG_LEVEL_ERROR, ERR_CIPHER_REPEAT_INIT)
#define  HI_ERR_CIPHER_INVALID_POINT          HI_DEF_ERR(MID_CIPHER, HI_LOG_LEVEL_ERROR, ERR_CIPHER_INVALID_POINT)
#define  HI_ERR_CIPHER_INVALID_PARA              HI_DEF_ERR(MID_CIPHER, HI_LOG_LEVEL_ERROR, ERR_CIPHER_INVALID_PARA)
#define  HI_ERR_CIPHER_FAILED_INIT               HI_DEF_ERR(MID_CIPHER, HI_LOG_LEVEL_ERROR, ERR_CIPHER_FAILED_INIT)   
#define  HI_ERR_CIPHER_FAILED_GETHANDLE               HI_DEF_ERR(MID_CIPHER, HI_LOG_LEVEL_ERROR, ERR_CIPHER_FAILED_GETHANDLE)   
#define  HI_ERR_CIPHER_FAILED_RELEASEHANDLE               HI_DEF_ERR(MID_CIPHER, HI_LOG_LEVEL_ERROR, ERR_CIPHER_FAILED_RELEASEHANDLE)   
#define  HI_ERR_CIPHER_FAILED_CONFIGAES               HI_DEF_ERR(MID_CIPHER, HI_LOG_LEVEL_ERROR, ERR_CIPHER_FAILED_CONFIGAES)   
#define  HI_ERR_CIPHER_FAILED_CONFIGDES               HI_DEF_ERR(MID_CIPHER, HI_LOG_LEVEL_ERROR, ERR_CIPHER_FAILED_CONFIGDES)   
#define  HI_ERR_CIPHER_FAILED_ENCRYPT               HI_DEF_ERR(MID_CIPHER, HI_LOG_LEVEL_ERROR, ERR_CIPHER_FAILED_ENCRYPT)   
#define  HI_ERR_CIPHER_FAILED_DECRYPT               HI_DEF_ERR(MID_CIPHER, HI_LOG_LEVEL_ERROR, ERR_CIPHER_FAILED_DECRYPT)   

/*SC错误码子码定义*/
enum hiSC_ErrorCode_E
{
    ERR_SC_NOT_INIT = 0,
    ERR_SC_REPEAT_INIT,
    ERR_SC_INVALID_POINT,
    ERR_SC_INVALID_PARA,
    ERR_SC_FAILED_INIT,
    ERR_SC_FAILED_SETPINMODE
};

/*SC错误码定义*/
#define  HI_ERR_SC_NOT_INIT                  HI_DEF_ERR(MID_SC, HI_LOG_LEVEL_ERROR, ERR_SC_NOT_INIT)  // 0xa031800   
#define  HI_ERR_SC_REPEAT_INIT               HI_DEF_ERR(MID_SC, HI_LOG_LEVEL_ERROR, ERR_SC_REPEAT_INIT)
#define  HI_ERR_SC_INVALID_POINT             HI_DEF_ERR(MID_SC, HI_LOG_LEVEL_ERROR, ERR_SC_INVALID_POINT)
#define  HI_ERR_SC_INVALID_PARA              HI_DEF_ERR(MID_SC, HI_LOG_LEVEL_ERROR, ERR_SC_INVALID_PARA)
#define  HI_ERR_SC_FAILED_INIT               HI_DEF_ERR(MID_SC, HI_LOG_LEVEL_ERROR, ERR_SC_FAILED_INIT)
#define  HI_ERR_SC_FAILED_SETPINMODE         HI_DEF_ERR(MID_SC, HI_LOG_LEVEL_ERROR, ERR_SC_FAILED_SETPINMODE)


enum hiPMoC_ErrorCode_E
{ 
    ERR_PMoC_NOT_INIT = 0,
    ERR_PMoC_REPEAT_INIT,
    ERR_PMoC_INVALID_POINT,
    ERR_PMoC_INVALID_PARA,
    ERR_PMoC_FAILED_INIT,
    ERR_PMoC_FAILED_MODE,
    ERR_PMoC_FAILED_READMODE,
    ERR_PMoC_FAILED_IRPOWERVAL,
    ERR_PMoC_FAILED_KEYLEDPOWERVAL,
    ERR_PMoC_INVALID_MODE,
/* led display time when arm is stand by, add by David Huang 2008-05-02 start */
	ERR_PMoC_FAILED_STANDBY
/* led display time when arm is stand by, add by David Huang 2008-05-02 end */
};

#define  HI_ERR_PMoC_NOT_INIT              HI_DEF_ERR(MID_PMoC, HI_LOG_LEVEL_ERROR, ERR_PMoC_NOT_INIT) /* 0xa0328000 */
#define  HI_ERR_PMoC_REPEAT_INIT           HI_DEF_ERR(MID_PMoC, HI_LOG_LEVEL_ERROR, ERR_PMoC_REPEAT_INIT)
#define  HI_ERR_PMoC_INVALID_POINT         HI_DEF_ERR(MID_PMoC, HI_LOG_LEVEL_ERROR, ERR_PMoC_INVALID_POINT)
#define  HI_ERR_PMoC_INVALID_PARA          HI_DEF_ERR(MID_PMoC, HI_LOG_LEVEL_ERROR, ERR_PMoC_INVALID_PARA)
#define  HI_ERR_PMoC_FAILED_INIT           HI_DEF_ERR(MID_PMoC, HI_LOG_LEVEL_ERROR, ERR_PMoC_FAILED_INIT)
#define  HI_ERR_PMoC_FAILED_MODE           HI_DEF_ERR(MID_PMoC, HI_LOG_LEVEL_ERROR, ERR_PMoC_FAILED_MODE)
#define  HI_ERR_PMoC_FAILED_READMODE       HI_DEF_ERR(MID_PMoC, HI_LOG_LEVEL_ERROR, ERR_PMoC_FAILED_READMODE)
#define  HI_ERR_PMoC_FAILED_IRPOWERVAL     HI_DEF_ERR(MID_PMoC, HI_LOG_LEVEL_ERROR, ERR_PMoC_FAILED_IRPOWERVAL)
#define  HI_ERR_PMoC_FAILED_KEYLEDPOWERVAL HI_DEF_ERR(MID_PMoC, HI_LOG_LEVEL_ERROR, ERR_PMoC_FAILED_KEYLEDPOWERVAL)
#define  HI_ERR_PMoC_INVALID_MODE          HI_DEF_ERR(MID_PMoC, HI_LOG_LEVEL_ERROR, ERR_PMoC_INVALID_MODE)
/* led display time when arm is stand by, add by David Huang 2008-05-02 start */
#define  HI_ERR_PMoC_FAILED_STANDBY        HI_DEF_ERR(MID_PMoC, HI_LOG_LEVEL_ERROR, ERR_PMoC_FAILED_STANDBY)
/* led display time when arm is stand by, add by David Huang 2008-05-02 end */

/***************
  DMAC模块
 ***************/

/*DMAC错误码子码定义*/
enum hiDMAC_ErrorCode_E
{
    ERR_DMAC_NOT_INIT = 0,
    ERR_DMAC_REPEAT_INIT,
    ERR_DMAC_INVALID_POINT,
    ERR_DMAC_INVALID_PARA,
    ERR_DMAC_FAILED_INIT,
    ERR_DMAC_FAILED_GETCHANNEL,
    ERR_DMAC_FAILED_MEMTRANS,
    ERR_DMAC_FAILED_PERTRANS,
    ERR_DMAC_FAILED_GETSTAT,
    ERR_DMAC_FAILED_LISTRESET,
    ERR_DMAC_FAILED_ADDLIST,
    ERR_DMAC_FAILED_LISTTRANS
};

/*DMAC错误码定义*/
#define HI_ERR_DMAC_NOT_INIT      HI_DEF_ERR(MID_DMAC , HI_LOG_LEVEL_ERROR, ERR_DMAC_NOT_INIT)
#define HI_ERR_DMAC_REPEAT_INIT   HI_DEF_ERR(MID_DMAC , HI_LOG_LEVEL_ERROR, ERR_DMAC_REPEAT_INIT)
#define HI_ERR_DMAC_INVALID_POINT HI_DEF_ERR(MID_DMAC , HI_LOG_LEVEL_ERROR, ERR_DMAC_INVALID_POINT)
#define HI_ERR_DMAC_INVALID_PARA  HI_DEF_ERR(MID_DMAC , HI_LOG_LEVEL_ERROR, ERR_DMAC_INVALID_PARA)
#define HI_ERR_DMAC_FAILED_INIT   HI_DEF_ERR(MID_DMAC , HI_LOG_LEVEL_ERROR, ERR_DMAC_FAILED_INIT)
#define HI_ERR_DMAC_FAILED_GETCHANNEL  HI_DEF_ERR(MID_DMAC , HI_LOG_LEVEL_ERROR, ERR_DMAC_FAILED_GETCHANNEL)        
#define HI_ERR_DMAC_FAILED_MEMTRANS  HI_DEF_ERR(MID_DMAC , HI_LOG_LEVEL_ERROR, ERR_DMAC_FAILED_MEMTRANS)        
#define HI_ERR_DMAC_FAILED_PERTRANS  HI_DEF_ERR(MID_DMAC , HI_LOG_LEVEL_ERROR, ERR_DMAC_FAILED_PERTRANS)        
#define HI_ERR_DMAC_FAILED_GETSTAT   HI_DEF_ERR(MID_DMAC , HI_LOG_LEVEL_ERROR, ERR_DMAC_FAILED_GETSTAT)        
#define HI_ERR_DMAC_FAILED_LISTRESET HI_DEF_ERR(MID_DMAC , HI_LOG_LEVEL_ERROR, ERR_DMAC_FAILED_LISTRESET)        
#define HI_ERR_DMAC_FAILED_ADDLIST   HI_DEF_ERR(MID_DMAC , HI_LOG_LEVEL_ERROR, ERR_DMAC_FAILED_ADDLIST)        
#define HI_ERR_DMAC_FAILED_LISTTRANS HI_DEF_ERR(MID_DMAC , HI_LOG_LEVEL_ERROR, ERR_DMAC_FAILED_LISTTRANS)        

/***************
  ETH模块
 ***************/

/*ETH错误码子码定义*/
enum hiETH_ErrorCode_E
{
    ERR_ETH_NOT_INIT = 0,
    ERR_ETH_REPEAT_INIT,
    ERR_ETH_INVALID_POINT,
    ERR_ETH_INVALID_PARA,
    ERR_ETH_FAILED_INIT
};

/*DMAC错误码定义*/
#define HI_ERR_ETH_NOT_INIT      HI_DEF_ERR(MID_ETH , HI_LOG_LEVEL_ERROR, ERR_ETH_NOT_INIT)
#define HI_ERR_ETH_REPEAT_INIT   HI_DEF_ERR(MID_ETH , HI_LOG_LEVEL_ERROR, ERR_ETH_REPEAT_INIT)
#define HI_ERR_ETH_INVALID_POINT HI_DEF_ERR(MID_ETH , HI_LOG_LEVEL_ERROR, ERR_ETH_INVALID_POINT)
#define HI_ERR_ETH_INVALID_PARA  HI_DEF_ERR(MID_ETH , HI_LOG_LEVEL_ERROR, ERR_ETH_INVALID_PARA)
#define HI_ERR_ETH_FAILED_INIT   HI_DEF_ERR(MID_ETH , HI_LOG_LEVEL_ERROR, ERR_ETH_FAILED_INIT)

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif /* __ESS_ERRCODE_H__ */
